### ISSUE TITLE
GNOME 40 support

### ISSUE THREAD

**Issue by PizzaLovingNerd** [dracula/gtk#105]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Hello, I was hoping we could see a GNOME 40 Shell theme with Dracula. The current one for GNOME 3.X needs to be updated to support GNOME 40, or else issues like this happen (A mix of Dracula and Adwaita)

![image](https://user-images.githubusercontent.com/13041099/113776733-1179cb00-96df-11eb-856c-32695cee3c5d.png)

Thanks in advance :)
- PizzaLovingNerd
(Edit to fix formatting)

**Comment by l3afblow3r** [comment]
Any change that the support for v4 causes problems in v3 and that we "maybe" would need a separate branch for v4?

**Comment by EliverLara** [comment]
Gnome 40 support added!
