### ISSUE TITLE
Changing Directory/Folder Color

### ISSUE THREAD

**Issue by abstract-arrow** [dracula/gtk#112]
Is there any way to change directory colors to something else?
I went through some files and looked for it but found nothing.
The directories icons are too dark for me

Currently, I'm using Gnome DE (Ubuntu 20.04)

![dev](https://user-images.githubusercontent.com/61705762/115161769-c1264400-a0b4-11eb-9d80-29ff881eee16.png)

**Comment by EliverLara** [comment]
Hi, you can easily change it with inkscape just by editing the `.svg` file
