### ISSUE TITLE
Bug on selected window preview at activities window on gnome 40

### ISSUE THREAD

**Issue by josemorista** [dracula/gtk#117]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![bug](https://user-images.githubusercontent.com/39710020/122708387-7484f380-d232-11eb-974f-8d1f7a284652.png)

If there are any maximized windows at the active workspace, the window is displayed with a left padding at windows picker from applications menu.

To fix, just remove the "padding: 0 16px 16px" from the .window-picker class.

Thx for the great work!

**Comment by EliverLara** [comment]
Thanks for sharing the fix! I've implemented it.
