### ISSUE TITLE
After installing Dracula theme, every shell theme conflicts with weird borders

### ISSUE THREAD

**Issue by kikifuku** [dracula/gtk#119]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![Screenshot from 2021-06-25 12-18-12](https://user-images.githubusercontent.com/52758895/123401448-77c00c80-d5af-11eb-88e4-207dc0823efd.png)
![Screenshot from 2021-06-25 12-12-30](https://user-images.githubusercontent.com/52758895/123400659-ac7f9400-d5ae-11eb-90e9-1b68e4d81d6a.png)

I use Pop!_OS 21.04.

I think the issue is the default shell theme get between the chosen shell theme and other widgets in the panel. I reinstalled gnome-shell, user theme extension and nothing changed.

**Comment by EjPlatzer** [comment]
I have the exact same issue on Pop!_OS 21.04. It seems like theme defaults to light. I've tried resetting completely and selecting dark theme, then installing the Dracula theme, but it still had the same result. I would love to see this fixed, it's very disruptive of the otherwise harmonious theme.
