### ISSUE TITLE
Where to add new icons?

### ISSUE THREAD

**Issue by mskf1383** [dracula/gtk#120]
Hi
I designed some new app icons for Dracula icon pack and want to push them to Dracula repository.
Where is it repository?
Thanks!

**Comment by The-Repo-Club** [comment]
@mskf1383 if you like send me the icons and if i like them i may add them to the Arch AUR package

**Comment by mskf1383** [comment]
https://mega.nz/file/YKoHjKCS#7dNuNYlN7C1LvDZ2o-Fhd5VGvV047ogtEEg5mSsvOaM
https://mega.nz/file/pPhDEKxC#UFd3JPApdCvq5k5q0eCylBjlfmFvZKz3bME9fDVrG9g
https://mega.nz/file/ADw3gajC#dwvY_GaWW9tqrN9GhZZrtKEH7hNQSBn8-H8N_VpWrkw
https://mega.nz/file/YbpjSASQ#k2_IgON7wTMq-9dv40IX-pJkj5c86bwc_OkdFf15XWw

There are **Atomic wallet** logo, **Element** logo, **Vlc** logo and Inkscape logo with another name (I just change it name because it don't work)

Thanks!
