### ISSUE TITLE
Broken edges

### ISSUE THREAD

**Issue by Jarif-Rahman** [dracula/gtk#121]
Edges are kind of broken.  
A screenshot from nautilus:   
![Screenshot from 2021-07-01 12-47-57](https://user-images.githubusercontent.com/64405720/124079164-a1bf7600-da6a-11eb-85d5-385965a9398e.png)  
If look closely edges are not straight. The screenshot was taken from natuilus, but I have seen this problem also on other apps like gnome-terminal.

**Comment by EliverLara** [comment]
Hi, sorry but I can't see wher the borders are boken

**Comment by Jarif-Rahman** [comment]
> Hi, sorry but I can't see wher the borders are boken

If you zoom a bit, you will see the edge isn't completely straight.    
Also I don't think a can help much to fix this bug right now, because I reported the bug when I was using ubuntu with gnome. Now I use <span title="btw I use arch :)">arch</span> with kde.
