### ISSUE TITLE
GTK theme not working on Inkscape

### ISSUE THREAD

**Issue by ElnuDev** [dracula/gtk#123]
The Dracula GTK theme is working perfectly on all of my GTK applications, but for some reason it isn't working in Inkscape, even though Inkscape's theme is set to "Use system theme (gtk-master)." Any ideas why? I'm not sure if this is the best place to ask for help, but I'm not sure where else to ask. Thanks in advance!

**Comment by EliverLara** [comment]
Hi, this is odd, it should work just by setting inkscape theme to "use system theme":

![Captura de pantalla de 2021-07-06 14-04-27](https://user-images.githubusercontent.com/9838260/124654441-2a238980-de64-11eb-9816-23fe82b7429c.png)

If it doesn't work you could try using the [ dracula theme for inkscape](https://draculatheme.com/inkscape).

**Comment by ElnuDev** [comment]
Yeah, I'm not sure what the issue is. That's exactly how I have it set up, but no luck. Anyhow, I got it working by manually installing the Dracula theme for Inkscape as you mentioned, so I guess I'll close this issue for now? Still weird though. Thanks for the help!
