### ISSUE TITLE
error gnome 40 vs dash to dock

### ISSUE THREAD

**Issue by tynguyen2k1** [dracula/gtk#124]
Looks like it looks pretty bad
![image](https://user-images.githubusercontent.com/64082226/124573006-57c3ff00-de73-11eb-8990-883b364ac226.png)
OS: Fedora 34

**Comment by EliverLara** [comment]
Hi, It seems that you are not using the version with support for gnome-shell v40:

![Captura de pantalla de 2021-07-06 13-25-51](https://user-images.githubusercontent.com/9838260/124650638-8cc65680-de5f-11eb-8a33-294008bd6efd.png)

**Comment by tynguyen2k1** [comment]
I installed by downloading using the GitHub.zip download option and extracting the .zip file to ~/.themes. What is my error?

**Comment by EliverLara** [comment]
Just replace the file `Dracula/gnome-shell/gnome-shell.css` with the one provided inside `Dracula/gnome-shell/v40/gnome-shell.css`

**Comment by tynguyen2k1** [comment]
Thanks, it worked !

**Comment by VarunVats9** [comment]
@EliverLara : I have the similar issue, the top right corner coming in gray color. I have replaced the file as well. the one you have mentioned above.
Using Ubuntu 21.10

![Screenshot from 2022-02-01 23-22-05](https://user-images.githubusercontent.com/2538815/152023966-981a89c6-835b-428e-88a3-842d57029452.png)

**Comment by dinojr** [comment]
> Just replace the file `Dracula/gnome-shell/gnome-shell.css` with the one provided inside `Dracula/gnome-shell/v40/gnome-shell.css`

Thanks, it's indeed much nicer. Is there a way to have gnome-shell automatically pick up this css ? Right now I'm using a link from ~/.themes/ to my clone of this git-repo and my gnome-shell (v43.1) is not using the v40 css.
