### ISSUE TITLE
No theme for gnome-system-monitor

### ISSUE THREAD

**Issue by rodrigoGA** [dracula/gtk#127]
gnome-system-monitor takes the default theme when using the dracula theme
![Captura de pantalla de 2021-07-14 11-29-22](https://user-images.githubusercontent.com/2334523/125640051-3d5f8b6e-9b22-4935-b85b-bb48aeee35f8.png)
With other themes, for example with the Materia theme, it does change colors.
![Captura de pantalla de 2021-07-14 11-29-52](https://user-images.githubusercontent.com/2334523/125640234-bfc5995d-819a-4475-833b-05a8afb57d87.png)

**Comment by EliverLara** [comment]
It should be fixed now with the support for gtk-4.0.

**Comment by wingarmac** [comment]
Same for me on Ubuntu 22.10 Kinetic Kudu with the 5.4.12 and the Adwaita-dark theme.
