### ISSUE TITLE
Gtk-warning messages

### ISSUE THREAD

**Issue by j0ker70** [dracula/gtk#134]
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/24 of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/32 of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/16@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/22@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/24@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/32@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/symbolic of theme Dracula has no size field`

I get these warning messages whenever I start evince. I am using dracula icon theme and color theme. I am running Ubuntu 20.04. Is there any way I can remove these warning mesages?

**Comment by eliu05** [comment]
I have the same issue here

**Comment by burrhole** [comment]
The icon theme linked in INSTALL.md is incomplete and doesn't include icons for those sizes. It also doesn't seem to be officially maintained as per this comment: https://github.com/dracula/gtk/issues/142#issuecomment-914643492 .
[This repo](https://github.com/matheuuus/dracula-icons) provides a much more fleshed out Dracula icon theme that will not throw those errors and provide icons for many more things.

**Comment by EliverLara** [comment]
That's because of what @burrhole says.
