### ISSUE TITLE
Gnome terminal is broken after installing latest

### ISSUE THREAD

**Issue by ddaws** [dracula/gtk#138]
After installing the latest Dracula GTK theme the Gnome terminal is visually broken, appearing transparent and showing fragments of frames rendered behind the terminal. Here is what it looks like 

![scrot](https://user-images.githubusercontent.com/1885328/130365291-2a26b3c0-8d01-41a1-9e7c-7849d3e002dc.png)

Running Gnome 40.4.0 and X11

Any help / suggestions / fixes is appreciated! Thank you :pray:

**Comment by ddaws** [comment]
I tried adding `@define-color text_view_bg #3b4252;` to `/usr/share/themes/Dracula/gtk-3.0/gtk.css` but am still seeing the same bug. Am I adding this to the right file?

**Comment by xaeioux** [comment]
Well, I got this fixed by installing Dracula theme on the gnome terminal, already faced this problem other times always fixed by installing the proper gnome terminal theme


https://draculatheme.com/gnome-terminal

**Comment by ddaws** [comment]
Thanks @xaeioux. Installing the gnome terminal theme fixed the terminal appearance while using the GTK theme :tada: Weird that this wasn't need before but happy to have it working :) 

I'm going to close this issue for now bc there is a fix, and the gnome-terminal package seems to imply the GTK theme isn't also supposed to be responsible for theming the terminal.
