### ISSUE TITLE
Favorite apps bar and background menu area are gray

### ISSUE THREAD

**Issue by xaeioux** [dracula/gtk#141]
Hello guys, how are you?

I've noticed that when you are  using gnome 40 with Dracula theme the Favorite apps bar and background menu area are gray
![image](https://user-images.githubusercontent.com/46939526/131864903-2305b78d-8a4a-4b0e-8ea0-3406cdee015d.png)

I'm using manjaro.

I found a theme based on Dracula that has it fixed, making a beautiful color harmony:
https://github.com/ZauJulio/Dracula-shell-40

Thank you for your time :)

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version,  please take a look to #124

**Comment by xaeioux** [comment]
Thanks @EliverLara worked like a charm
