### ISSUE TITLE
Where is the icon file repo

### ISSUE THREAD

**Issue by thesobercoder** [dracula/gtk#142]
I'm really struggling to understand where this `https://github.com/dracula/gtk/files/5214870/Dracula.zip` file is located. I don't see this file in the repository. The reason I ask is, I'd rather clone that repo inside `~/.icons` and do a `git pull` to keep it updated instead of having to download it manually every time.

**Comment by EliverLara** [comment]
Hi, actually there is no formal repository for icons, the url you mention is simply a link to a `.zip` file located in some issue comment.

**Comment by thesobercoder** [comment]
Would have been great if that were a repo.
