### ISSUE TITLE
feature request - don't show hints when hovering over minimize maximize close traffic light

### ISSUE THREAD

**Issue by dreamcat4** [dracula/gtk#145]
Hey there,
I don't know if you would be interested in this, however I find that the little overlay ontop of these maximize - minimize buttons is distracting. Because they are so small and tiny it looks kinda untidy and dirty marks when you are hovering the cursor itself occluding the colored circles

The other reason is because the color already reminds us which button does what action. So we already have a clear indication and knowledge before hovering over them

* If you don't like this suggestion and prefer the current existing behaviour...
  *  please say so
  * Then I won't have to waste time bothering to make a pull request for those changes
* If you do like this change but prefer to make the changes yourself
  * Please say so
  * Then i don't have to duplicate the work for no reason
* If you do like this change but it's something occuring further upstream (not in your code)
  * Please say so
* If you do like this change but don't have the time for it
  * Please say so
  * Any extra advice or quick hints where to look in the theme is very much welcome

And will proceed accordingly. Many thanks
Good day

**Comment by EliverLara** [comment]
HI, Thanks for your suggestions, but I'd like to keep the actual behaviour, Thanks.

**Comment by dreamcat4** [comment]
no problem!

actually i have some further comment to add.... while trying to modify this theme, and change those few little icons. i then came to realize what a total mess these linux icon themes generally are. i don't mean your theme is any worse than the other ones!

just it seems like really bad ecosystem with no clear simple standards. and the way the template SVG files are generating the other icon files. it is a fraught process. from hacking a badly written python script to the writing my own hack of a shell script to work ontop of the other hack. and overwrite other badly inconsistently named files.

i sort of? managed to do most of it by myself in the end. at least statically. however dynamic behaviour? nope.

for example:

* changing the color or brightness when hovering with the mouse... i did not manage to do that one
* having the inactive window's icons be a different color to those of the active window - again: it was too confusing for me. because so many duplicate similar names of same icon every place.

this isn't your fault or anything. it just seems well IDK... maybe a neglected side of this whole icon theming pursuit on linux here. for example if we could instead use *symlinks* heaven forbid. to cut down the total number of duplicate icons. or otherwise some makefile build task. or meson, or cmake, or `just` (which is the rust version of make)

anyhow it doesn't matter. all i wanted to say to record my experience there. for posterity or whatever.
