### ISSUE TITLE
Corners are missing in the calendar and event widget in Gnome (40.4.0)

### ISSUE THREAD

**Issue by Casualnudism** [dracula/gtk#147]
Corners are missing in the calendar and event widget in Gnome (40.4.0). This is not an issue using the default theme (Adwaita).

![98812](https://user-images.githubusercontent.com/74130815/135094810-9617b469-35d0-4835-8deb-3dc0a9193281.png)

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version,  please take a look to #124

**Comment by Casualnudism** [comment]
Solution worked! Thanks for your excellent work, most appreciated!
