### ISSUE TITLE
Inconsistent button shading on hover in Gnome (40.4.0) panel/shell

### ISSUE THREAD

**Issue by Casualnudism** [dracula/gtk#148]
Inconsistent button shading on hover in Gnome (40.4.0) panel/shell. This only affects time & date button. This is not an issue using the default theme/shell. 

![98813](https://user-images.githubusercontent.com/74130815/135099226-f67ba8e6-c6d9-4573-9c71-7e168fd88201.png)

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version,  please take a look to #124

**Comment by Casualnudism** [comment]
Solution worked! Thanks for your excellent work, most appreciated!
