### ISSUE TITLE
UI Bug - Linux Mint 20.2 Cinnamon

### ISSUE THREAD

**Issue by konrascher3** [dracula/gtk#149]
After installing the Dracula GTK theme, the control-elements do not change. Is there a fix available for this issue?

[Bug](https://ibb.co/0QzkYs6)

[Bug](https://ibb.co/RYX2cPn)

**Comment by EliverLara** [comment]
Hi, it looks similar to #140, Could you test if the proposal solution there works for you?

**Comment by konrascher3** [comment]
Thank you for the quick reply!

I moved the gtk-master folder from _/home/.themes_ to _/usr/share/themes_ as purposed, but the problem still persists. It looks like the bug affects the "controls" - part of the skin.

[Directories](https://ibb.co/sg95L5k)

Did I miss something?

**Comment by konrascher3** [comment]
I forgot to post my system-specs, maybe [this](https://ibb.co/KhWrw9N) helps.

**Comment by EliverLara** [comment]
This is odd, I've tested in my cinnamon desktop and everything looks good:

![Captura de pantalla de 2021-10-03 18-19-40](https://user-images.githubusercontent.com/9838260/135775357-ef6938cd-0820-4ba4-84af-034eb7f0eade.png)
![Captura de pantalla de 2021-10-03 18-21-31](https://user-images.githubusercontent.com/9838260/135775361-0fd05fb9-c52c-43f5-9d4e-d49e66d4985f.png)

**Comment by konrascher3** [comment]
Hmm, I see...

I switched to Ubuntu and it seems to work fine now, thanks for your help though!
