### ISSUE TITLE
Question: is it possible to use this theme in snaps?

### ISSUE THREAD

**Issue by dinandmentink** [dracula/gtk#153]
With newer versions of ubuntu using snaps for more software I have more and more applications reverting to the default theme. Is there a way to use the Dracula theme for snaps?

**Comment by EliverLara** [comment]
Hi, there is not an official snap port of this theme but there are some third party ports like [this](https://snapcraft.io/dracula-gtk-theme) (I've not tested it) that could help you.

**Comment by dinandmentink** [comment]
Thanks for the response. I'll have a look and try to respond with a quick report.
