### ISSUE TITLE
[Partially Solved] White background in some menus.

### ISSUE THREAD

**Issue by Random-Person213** [dracula/gtk#155]
Some menus seem to be white, here is an example
(https://user-images.githubusercontent.com/78260512/143869882-d9a945f3-a106-4194-86ba-25a89d803283.png)
I believe the reason is that gnome is thinking that the theme is light theme, here is an example:
(https://user-images.githubusercontent.com/78260512/143870062-30833de7-bd1c-43ce-994b-b2348af540ad.png)
This is in Pop!_OS 20.04

**Comment by Random-Person213** [comment]
Fix: https://github.com/dracula/gtk/commit/9d6f406e51fe5fdeddb0ca71224b81faf288e855

**Comment by Random-Person213** [comment]
Partial fix for Pop!_OS:
-----------------------------------------------------------------------------------------------------------
1. Install this extension: https://extensions.gnome.org/extension/19/user-themes/
2. Install gnome-tweaks `sudo apt install gnome-tweaks`
3. Open Tweaks (aka gnome-tweaks)
4. Go to appearance tab
5. Choose Pop-dark in "Shell"
-----------------------------------------------------------------------------------------------------------
Why I call this a "Partial fix" is because the theme is still registered as a "light" theme in the settings app, but the menus are now dark and not white.
Still waiting for a fix to make the theme registered as a dark theme.

**Comment by EliverLara** [comment]
Hi could you test if renaming the theme's folder fro 'Dracula' to 'Dracula-dark' fixes this issue, please?

**Comment by Random-Person213** [comment]
Thanks for your help, that did work.
