### ISSUE TITLE
Some applications does not support the theme properly

### ISSUE THREAD

**Issue by JyotirmayBarman** [dracula/gtk#156]
# Some applications does not support the theme properly, although these apps support [White Sur](https://github.com/vinceliuice/WhiteSur-gtk-theme) theme perfectly.
## Virtualbox
![Virtualbox](https://user-images.githubusercontent.com/56916274/143256807-caed4705-1908-41e8-84f6-ec011d054e6f.png)

## Extensions app
![image](https://user-images.githubusercontent.com/56916274/143257017-4ea73882-ece0-4255-a2e9-86467c32cfe5.png)

**Comment by dbasinge** [comment]
Think this theme has not added gtl4 support yet and WhiteSur has.

**Comment by EliverLara** [comment]
Hi, that's something related with gtk-4 support, I will try to add it ASAP

**Comment by OlaoluwaM** [comment]
Hey, @EliverLara I would like to help with that! Any way I can?

**Comment by EliverLara** [comment]
Initial support for gtk-4 has been added!

**Comment by dbasinge** [comment]
Still missing on Extension app for me (Fedora 35, Gnome 41)

**Comment by OlaoluwaM** [comment]
Hi, maybe try [this](https://itsfoss.com/flatpak-app-apply-theme/) or [this](https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html)

**Comment by dbasinge** [comment]
> Hi, maybe try [this](https://itsfoss.com/flatpak-app-apply-theme/) or [this](https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html)

Not using Gnome Extension as flatpak app. Flatpak apps look fine.

**Comment by OlaoluwaM** [comment]
Well, do you have Dracula set as your applications and shell theme? Any differences in your setup because I also run Fedora 35 with Gnome 41 and it works for me
