### ISSUE TITLE
Want to help with support for GTK 4

### ISSUE THREAD

**Issue by OlaoluwaM** [dracula/gtk#158]
Hey everyone! Love the theme. I have Dracula for pretty much everything except flatpaks that use gtk4, those ~~beasts~~ applications are ruining my aesthetics and I would like to fix them any way I can because.....OCD.

I am creating this issue to ask for a bit of guidance on how I can add GTK 4 support, there doesn't seem to be much documentation on this. Thanks!

**Comment by EliverLara** [comment]
Initial support for gtk-4 has been added!
