### ISSUE TITLE
Ligth Elements in Gnome Cosmic

### ISSUE THREAD

**Issue by JuniorCristian** [dracula/gtk#162]
> I use Pop!_OS 21.04 with Cosmic interface, some windows stay in Light Theme on Top Bar

![Captura de tela de 2021-12-17 13-47-13](https://user-images.githubusercontent.com/30303961/146579108-73f93b72-c453-4fe9-844b-2f95f532d482.png)

![Captura de tela de 2021-12-17 13-48-06](https://user-images.githubusercontent.com/30303961/146579173-e4a7a43c-2cbc-4905-82d5-52d1041d53d8.png)

**Comment by EliverLara** [comment]
Hi could you test if renaming the theme's folder from 'Dracula' to 'Dracula-dark' fixes this issue, please?

**Comment by JuniorCristian** [comment]
> Hi could you test if renaming the theme's folder from 'Dracula' to 'Dracula-dark' fixes this issue, please?

No exactaly, the system just put the default Pop_dark theme in parts that was in ligth

**Comment by EliverLara** [comment]
@JuniorCristian did you set the gnome-shell theme to dracula?

**Comment by JuniorCristian** [comment]
> @JuniorCristian did you set the gnome-shell theme to dracula?

I set the theme with Gnome Tweaks

**Comment by EliverLara** [comment]
Ok, so you may be using the wrong shell theme version, please take a look to #124
