### ISSUE TITLE
Weird border around dash-to-dock

### ISSUE THREAD

**Issue by dbasinge** [dracula/gtk#163]
Getting a weird border around dash-to-dock extension. Not seeing on other themes.

![Screenshot from 2021-12-21 11-20-12](https://user-images.githubusercontent.com/2634758/146963657-06899225-0ea7-4d0e-ba21-2fb67c45bdb6.png)

**Comment by dbasinge** [comment]
Example for other theme.
![Screenshot from 2021-12-21 11-24-23](https://user-images.githubusercontent.com/2634758/146965752-551d88f9-3b0c-439d-a7d5-fe1642202dfa.png)

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version, please take a look to #124
