### ISSUE TITLE
GTK 4 window borders transparent

### ISSUE THREAD

**Issue by burrhole** [dracula/gtk#164]
With the current GTK4 theme, the window borders are all transparent, creating a weird floating-style effect in tiling WMs, which does not occur when using Adwaita.
For example. here is a screenshot of two GTK4 apps, helvum and easyeffects, in Swaywm:
![image](https://user-images.githubusercontent.com/31171855/147006759-4d6b2ad4-bcaa-4a3a-8dcc-30410ad704f2.png)

**Comment by EliverLara** [comment]
It was fixed with e9a65ce1420628281c5a3206b296882e7c295473
