### ISSUE TITLE
Dracula-shell-40: No ''Do Not disturb'' button + errors

### ISSUE THREAD

**Issue by bitterhalt** [dracula/gtk#165]
In Ubuntu 21.10 I got no do not disturb button with Ant Dracula theme
![draculabugi](https://user-images.githubusercontent.com/95308907/147370297-bdfd743c-ceab-4401-b24c-47c3a3870e12.png)

![Screenshot from 2021-12-23 20-54-22](https://user-images.githubusercontent.com/95308907/147281890-9676bcfa-8659-41b3-8669-72a2bd6555e5.png)

**Comment by blinxio** [comment]
Same issue here

**Comment by EliverLara** [comment]
Thanks for reporting, it should be fixed now!

**Comment by blinxio** [comment]
> Thanks for reporting, it should be fixed now!

Yes, the button is here, but if we are nitpicking right now, the button is not centered according to the Do not disturb switch. It's below it. Besides that, it's all good! Thank you so much!

**Comment by bitterhalt** [comment]
> Thanks for reporting, it should be fixed now!

Thanks! it works perfect now!

**Comment by EliverLara** [comment]
Thanks @blinxio, misaligned button was fixed :)
