### ISSUE TITLE
Release a new tag

### ISSUE THREAD

**Issue by ericdallo** [dracula/gtk#167]
Hello, I loved the new cursor themes!
Awesome work!
I'm trying to add support for the cursor on [Nix](https://github.com/NixOS/nixpkgs), and releasing a new version would make things easier, is it possible to generate a new release?

**Comment by ericdallo** [comment]
c/c @EliverLara

**Comment by EliverLara** [comment]
[New release](https://github.com/dracula/gtk/releases/tag/v3.0) is ready :)
