### ISSUE TITLE
Add initial support/api compatibility for libadwaita (GTK4)

### ISSUE THREAD

**Issue by ghost** [dracula/gtk#170]
With the release of Gnome 42 nearing and standard applications slowly but surely switching from libhandy to libadwaita (e.g. EasyEffects) it would be nice if these applications are correctly themed.

Reference:
[Overview of libadwaita and theming it](https://blogs.gnome.org/alatiera/2021/09/18/the-truth-they-are-not-telling-you-about-themes/)
[libadwaita API Specs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/migrating-libhandy-1-4-to-libadwaita.html)

Current Behaviour:
Operating System: Current Arch Linux (Gnome 41)
"GTK_THEME=Dracula easyeffects"

![Screenshot1](https://user-images.githubusercontent.com/16107593/151661235-1889a670-8e32-4235-bf91-ce3e0e9ad3b8.png)
![Screenshot from 2022-01-29 13-33-25](https://user-images.githubusercontent.com/16107593/151661243-c8a3c4a8-a322-44b1-a5fb-dc1b4de2c4d1.png)

Most things actually look ok - seems only some finetuning is neccessary (e.g. spacing seems off)

**Comment by caiocutrim** [comment]
+1 I would love to see this theme implemented in gnome 42 👍🏼, for a while I'm using the default adwaita dark theme variant and dracula theme in my vscode.

**Comment by benneti** [comment]
For people happy with just the color scheme there is this https://github.com/odziom91/libadwaita-themes ,
which fits in much better than the standard adwaita dark style, see:
![image](https://user-images.githubusercontent.com/11725645/163140582-59bf3cdb-fbe0-4035-a5d6-f5fe6aa2c634.png)

**Comment by ran-dall** [comment]
For those of you waiting for LibAwaita compatibility...

We're starting to look into this with @EliverLara in #208, as we'll have to move a few things around.

In the meantime, you can #200 to use the theme with LibAwaita. I'll try to keep that PR in line with the changes made with LibAwaita so you guys can keep up with the changes.

**Comment by Cornul11** [comment]
For those who want a more consistent look, for gtk-4.0 and libadwaita in general, you may as well, in the meanwhile, use this tool that I've created: [GTK4ThemeAdapter](https://github.com/Cornul11/GTK4ThemeAdapter)

**Comment by ran-dall** [comment]
@Cornul11 Great addition! Thank you for sharing! Gradiance is also a very good, semi-supported by GNOME option, as well.
