### ISSUE TITLE
[Issues] very small app grid

### ISSUE THREAD

**Issue by vanillamatcha** [dracula/gtk#173]
I have a issues, when I use the "dash to panel" extension, the view from the app grid is very small. Even though already using shell for gnome version 40+.
![Screenshot from 2022-02-13 00-21-54](https://user-images.githubusercontent.com/36553432/153982832-371c90f8-2e24-4543-9419-275d7e7ffe24.png)

btw thanks for making such a beautiful theme :3

**Comment by EliverLara** [comment]
That was fixed with 317d6cbb92c6891a6a0762c2914047ffed87fdff
