### ISSUE TITLE
Mate: "This theme will not look as intended because the required GTK+ theme 'Ant-Dracula' is not installed

### ISSUE THREAD

**Issue by SlidingHorn** [dracula/gtk#179]
![Screenshot at 2022-03-14 01-13-16](https://user-images.githubusercontent.com/6623121/158108962-897b6d17-5e47-46c5-9af0-25858c3e1716.png)
Per the instructions:

> Download using the [GitHub .zip download](https://github.com/dracula/gtk/archive/master.zip) option and extract the .zip file to the themes directory i.e. /usr/share/themes/ or ~/.themes/ (create it if necessary)

I've attempted extracting it to both locations, and get the same issue. When loading the theme selection application in MATE, I receive the error in the title.

**Comment by EliverLara** [comment]
Fixed with ab40fa908a33a31c800fc544a4e6895da3d886e6
