### ISSUE TITLE
[Request] Libadwaita theme

### ISSUE THREAD

**Issue by yavko** [dracula/gtk#180]
tl;dr
basicly if some vars are set in the gtk 4 theme, theme should work. Though I'm not 100% sure.

Yes this is a thing!
![image](https://user-images.githubusercontent.com/15178513/160342031-48f8bdb6-23b9-4b8b-ac13-e3fd26adda54.png)
> I made this example in 2 minutes, but as you can see it doesn't match that well

Anyways for more details: https://www.reddit.com/r/gnome/comments/tp3v7d/theming_in_libadwaita_is_pretty_nice/?sort=new

**Comment by xukashi** [comment]
+1

**Comment by yavko** [comment]
Anyways this is a duplicate #170
