### ISSUE TITLE
Application names are not shown

### ISSUE THREAD

**Issue by victoraugusto6** [dracula/gtk#182]
I'm having trouble seeing the name of the applications, where I can only see if I leave the mouse in focus.
No mouse in focus:
![image](https://user-images.githubusercontent.com/48570599/162193367-e8263e81-8742-4292-bcaf-cc66622ec849.png)

With mouse in focus:
![image](https://user-images.githubusercontent.com/48570599/162193502-2a18cc15-1ac8-4c36-8ef2-ff9cbd36cd58.png)

**Comment by EliverLara** [comment]
Hi, It seems that you have not applied the shell theme, you have to install [this](https://extensions.gnome.org/extension/19/user-themes/) extension and then select 'Dracula' in the shell section of tweaks.

**Comment by victoraugusto6** [comment]
> Hi, It seems that you have not applied the shell theme, you have to install [this](https://extensions.gnome.org/extension/19/user-themes/) extension and then select 'Dracula' in the shell section of tweaks.

Hello, @EliverLara 
Thanks for helping!

I enable this theme in shell config using Gnome Tweaks:
![image](https://user-images.githubusercontent.com/48570599/168290878-8e81edfc-7269-4b0d-bac3-63618f90e417.png)

**Comment by victoraugusto6** [comment]
I believe the problem is because the text contains the same color as the background.

**Comment by EliverLara** [comment]
This should be solved using the right version of the gnome-shell theme, plase take a look to #124

**Comment by ran-dall** [comment]
@victoraugusto6 You must install the `User Theme` extension @EliverLara provided the link. When you set it through Tweaks, it seems you're only applying the styles to the GNOME shell. That extension will load the styles for LibHandy applications. You can use the make file in #200 to deploy the styles for LibAwaita. You'll need to deploy both to get consistent styles across GNOME 40+.
