### ISSUE TITLE
Missing the Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [dracula/gtk#185]
The project is currently missing the Issue Templates. If you would like to add them, then I would submit a PR with some relevant issue templates. Let me know what you think about it.

**Comment by ran-dall** [comment]
@FahimFBA That would be excellent. Otherwise, I could do this as well, if you prefer. Thank you for the offer to help.

**Comment by FahimFBA** [comment]
Thank you @ran-dall. I am starting to do that.
