### ISSUE TITLE
Not the same background color on button pannel

### ISSUE THREAD

**Issue by omgronny** [dracula/gtk#186]
On the gnome 41.5 (manjaro) the background of applications icons are not the same as background of the bottom pannel

![image](https://user-images.githubusercontent.com/68964770/166634621-cd7cb0bc-939a-4157-8493-88001993916f.png)

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version, please take a look to https://github.com/dracula/gtk/issues/124
