### ISSUE TITLE
KDE Windows docoration: small sneeze on white on corners

### ISSUE THREAD

**Issue by bitterhalt** [dracula/gtk#187]
I use Dracula KDE Window docorations and colors scheme and this show typically on some dark/grey backgrounds.
![Screenshot_20220507_121643](https://user-images.githubusercontent.com/95308907/167248277-6a0247cf-c330-432d-a853-f6053b4cd26e.png)

Btw happens also with your Nordic thme.

**Comment by EliverLara** [comment]
That was an issue with aurorae as you can see [here](https://bugs.kde.org/show_bug.cgi?id=395725)
