### ISSUE TITLE
Ubuntu 22.04 Dock style issues

### ISSUE THREAD

**Issue by drafenous** [dracula/gtk#188]
When using Ubuntu 22.04 with default centered Dock, I'm having style issues.

![image](https://user-images.githubusercontent.com/8341200/167501908-d427eae4-762a-416c-8046-e5142303049e.png)

The dock is with a strange border outside the dock.
How to fix that?

Thanks for your time!

**Comment by EliverLara** [comment]
Hi, Are you sure you're using the right version of the theme provided [here](https://github.com/dracula/gtk/blob/master/gnome-shell/v40/gnome-shell.css) ?

**Comment by drafenous** [comment]
> Hi, Are you sure you're using the right version of the theme provided [here](https://github.com/dracula/gtk/blob/master/gnome-shell/v40/gnome-shell.css) ?

Yes, i'm using.

**Comment by EliverLara** [comment]
HI, Could you please test if [this css](https://github.com/dracula/gtk/blob/dash/gnome-shell/v40/gnome-shell.css) file fixes the issue?

**Comment by drafenous** [comment]
> HI, Could you please test if [this css](https://github.com/dracula/gtk/blob/dash/gnome-shell/v40/gnome-shell.css) file fixes the issue?

Same problem :(

**Comment by xukashi** [comment]
> > HI, Could you please test if [this css](https://github.com/dracula/gtk/blob/dash/gnome-shell/v40/gnome-shell.css) file fixes the issue?
> 
> Same problem :(

do you happen to use Blur My Shell?

**Comment by pasan93** [comment]
> HI, Could you please test if [this css](https://github.com/dracula/gtk/blob/dash/gnome-shell/v40/gnome-shell.css) file fixes the issue?

Thanks, this works for me. However I'm still having a minor issue.
When I hover the dock it doesn't highlight the icons anymore.

![WhatsApp Image 2022-05-30 at 12 22 04 PM](https://user-images.githubusercontent.com/29046066/170936586-b9bd744b-d674-4b3e-9da1-69e79611d37e.jpeg)

This is a screenshot from my laptop which is on PoP!_OS 21.10

![WhatsApp Image 2022-05-30 at 12 24 22 PM](https://user-images.githubusercontent.com/29046066/170936701-97cba8cf-6550-433e-8517-b79166085b74.jpeg)


Do you have any idea how to fix this issue?

**Comment by drafenous** [comment]
With Blur my shell enabled:
![image](https://user-images.githubusercontent.com/8341200/170985736-cb138caf-1620-42c8-9bff-76ce392ea4c2.png)

**Comment by ran-dall** [comment]
I believe there are several problems here. 

- First is that DashToDock (and Floating Dock) only have compatibility with 41 (which is v71). Many of the fixes for 42 are not merged yet.
- Furthermore, v72 (for 42) has been rejected by GNOME (https://extensions.gnome.org/review/32340). 
- If you are using the git version, you'll see the breakage in several places if you dig a little. Don't get me wrong, it's useable; but I'd hardly consider it stable.

I think with all this considered, it may be hard for us to 'fully' address the problems with DashToDock (or its forks) until the dust has settled a bit. NTM, GNOME is in a very transitional state itself.

**Comment by pasan93** [comment]
> I believe there are several problems here.
> 
>     * First is that DashToDock (and Floating Dock) only have compatibility with 41 (which is v71). Many of the 'necessary' fixes for 42 are not merged yet.
> 
>     * The initial package, v72 (for 42), has been rejected by GNOME (https://extensions.gnome.org/review/32340).
> 
>     * If you are using the git version, you'll see the breakage in several places if you dig a little. Don't get me wrong, it's useable; but I'd hardly consider it stable.
> 
> 
> I think with all this considered, it may be hard for us to 'fully' address the problems with DashToDock (or its forks) until the dust has settled a bit. NTM, GNOME is in a very transitional state itself.

https://github.com/dracula/gtk/issues/192

**Comment by ran-dall** [comment]
#194 should fix the last of the current problems I see with the dock. You **need to** copy `gnome-shell/v40/gnome-shell.css` and paste it over the file located at `gnome-shell/gnome-shell.css.` Otherwise, the styles for >=40 will not be applied (in fact, the regular one doesn't have the styles for Dash to Dock at all). 

If your background is messed up, then you didn't do the step above correctly. 

FWIW that PR is for the `dash` branch.

**Comment by ran-dall** [comment]
@EliverLara This can be closed as well now that #194 is merged, I suppose.
