### ISSUE TITLE
how to remove ~ via  v16.15.0 from the terminal?

### ISSUE THREAD

**Issue by updwnheadlights** [dracula/gtk#189]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
the ~ via  v16.15.0 showup on every command 
![image](https://user-images.githubusercontent.com/68861149/168074801-3672d5be-8690-4619-9567-8304611aad3a.png)

**Comment by EliverLara** [comment]
Hi, this issue is related with your shell prompt not with with the theme.
