### ISSUE TITLE
Transparent line in chromium

### ISSUE THREAD

**Issue by d8a-base** [dracula/gtk#195]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![dracula-gtk-chrom1](https://user-images.githubusercontent.com/106983979/172189772-9569528a-3782-4883-93f5-ba1c155dc65e.png)

Chromium (Version 102.0.5005.61) displays a transparent line between searchbar and the website.

I'm using Openbox with picom as compositor but this bug was easily reproducible in a virtual machine with XFCE and their compositor. 

Dracula was installed via AUR package: https://aur.archlinux.org/packages/dracula-gtk-theme

This transparent line in not present in other GTK themes I tried.

**Comment by rc2dev** [comment]
Same issue on Brave (Version 1.40.107 Chromium: 103.0.5060.53). installed Dracu

**Comment by rc2dev** [comment]
Same issue on Brave (Version 1.40.107 Chromium: 103.0.5060.53).

I installed Dracula by cloning the repo, and I'm tracking master.
