### ISSUE TITLE
Smaller icons are really hard to see

### ISSUE THREAD

**Issue by NovaViper** [dracula/gtk#196]
I'm using the [Dracula KDE theme from the KDE store](https://store.kde.org/p/1370871) and it's extremely hard to see the smaller icons in the dolphin filebrowser and many other (they're still grey instead of changing to white) as seen in the screenshot in Dolphin. I'm using OpenSUSE Tumbleweed Leap 15.4 and KDE Plasma 5.24
![Screenshot_20220611_105708](https://user-images.githubusercontent.com/7191115/173197909-916c817e-f3f3-421b-8b78-9cad3d95c580.png)

**Comment by ran-dall** [comment]
@NovaViper You need to install a compatible Icon theme. There are 3. 2 of which are not really maintained. I would recommend https://github.com/vinceliuice/Tela-circle-icon-theme, which is maintained.

**Comment by NovaViper** [comment]
> @NovaViper You need to install a compatible Icon theme. There are 3. 2 of which are not really maintained. I would recommend https://github.com/vinceliuice/Tela-circle-icon-theme, which is maintained.

Ah ok! I went and found the icon set and it works!
