### ISSUE TITLE
Cinnamon grouped window list visibility problem

### ISSUE THREAD

**Issue by purpleleaf** [dracula/gtk#197]
Using wallpaper with light areas is difficult to understand if an application is already opened or not.
I think that providing a non transparent (or less transparent) panel background could solve the problem. I think that should be difficult to find a color settings that could work with every wallpaper
See the attacched images.
![Schermata del 2022-06-15 14-49-36](https://user-images.githubusercontent.com/1252406/173832268-fadf1d27-16c9-480a-a795-e6da20485298.png)
t
![Schermata del 2022-06-15 14-55-07](https://user-images.githubusercontent.com/1252406/173832272-146d4e9e-7b6e-4a42-88f4-33512b9bf5da.png)

**Comment by EliverLara** [comment]
Thanks for reporting, that should be fixed with 87d2e6e5c4c80d131f2b61254d0b5e3dcd3a6772
