### ISSUE TITLE
contextual menu are the same color as background in pcmanfm

### ISSUE THREAD

**Issue by FredericGuilbault** [dracula/gtk#20]
contextual menu are the same color as background in pcmanfm (and others)
The original ant  theme have the same thing but it have a 1px black border around it to distinguish the menu from the background

https://imgur.com/a/pKi4ceD

**Comment by azisnaufal** [comment]
i think you should turn on compositor to create a shadow behind the contextual menu.
this theme is work great with compositor like compiz, and so on...

**Comment by FredericGuilbault** [comment]
It's to be distributed on a raspberryPi, so performance is a big deal. compiz is out of the scope for my usecase. 

maybe it's just not designed for my usecase.

**Comment by EliverLara** [comment]
Hi @FredericGuilbault , What is your pcmanfm version? on 1.3.1 it looks good for me:

![Captura de pantalla de 2019-03-08 14-35-58](https://user-images.githubusercontent.com/9838260/54054433-c283a380-41af-11e9-9ccb-e72dceeefa6a.png)

**Comment by FredericGuilbault** [comment]
version number is 1.2.5-3+rpi5
