### ISSUE TITLE
theme didnt apply on ubuntu software

### ISSUE THREAD

**Issue by jobcmax** [dracula/gtk#204]
for some reason the dracula theme didnt apply on ubuntu software app
picture taken on ubuntu 22.04 LTS

![image](https://user-images.githubusercontent.com/80607620/178106501-c467389b-2ebc-47a9-9800-7d6c93d53f78.png)

**Comment by ran-dall** [comment]
@JobMaxcello Most likely this is because `gnome-software` uses LibAwaita or because you have it installed as a FlatPak. If it's not a FlatPak, you can use the make file #200 to install the themes for use with LibAwaita.

**Comment by tylert93** [comment]
@ran-dall  Could you please provide some more details of how to use this command and implement the Dracula theme across all applications, thanks

**Comment by ran-dall** [comment]
@tylert93 Sure. essentially `GTK-3` and `GTK-4` styles are different and also `GTK-4` expects theme files in an XDG-friendly location. The `make` file just automates that for you.

Another idea is to just use the [Grandience](https://usegradience.github.io/), which might be slightly more official (from a GNOME standpoint). They have an official Dracula theme.
