### ISSUE TITLE
Window buttons are missing in libadwaita styled windows.

### ISSUE THREAD

**Issue by BurgundyDev** [dracula/gtk#206]
When applying the theme to GTK-4 - i.e. copying the files from the gtk-4.0 folder to $HOME/.config/gtk-4.0, it can be observed that windows styled in libadwaita are missing their window buttons. The buttons are still interactable and in their proper places, but are not generally visible, making the theme virtually unusable.

GTK-4 app focused
![image](https://user-images.githubusercontent.com/24825890/179375305-755c719e-ff0e-402f-9ff1-950eaff3d9af.png)

GTK-3 app focused
![image](https://user-images.githubusercontent.com/24825890/179375318-e4bccdd0-2142-4125-aa23-5852a189923b.png)

**Comment by floydfire** [comment]
Have you tried to put the assets folder from the dracula theme to .config? cause that seems to be working for me.. to be clear i did this: 
Copied the files under `~/.themes/Dracula/gtk-4.0` to `~/.config/gtk-4.0` then copied the folder `assets` from `~/.themes/Dracula/` and put that into `~/.config/` that seems to make the buttons appears like other windows.

I'm learning linux so i'm not really that experienced to know if that can cause any other problems, but right now everything is working fine for me, i see you using Fedora, i'm using Nobara (which is fedora but with some gaming tweaks) so i think that maybe copying the files should works for you also...

**Comment by BurgundyDev** [comment]
Hey @floydfire, You were, in fact, correct. It was either assets, src or metacity-1 that fixed it. Closing as it was my mistake, although I wish this was better documented.
