### ISSUE TITLE
Broken styles on Dashboard Dock

### ISSUE THREAD

**Issue by ran-dall** [dracula/gtk#207]
Currently, the styles that should work on the standard Dashboard's Dock are broken. See attached image...

![image](https://user-images.githubusercontent.com/17261190/183268873-277d8722-37ba-423f-8d8b-052ef8af238c.png)

**Comment by EliverLara** [comment]
Hi @ran-dall,Could you provide more info about your OS please?

**Comment by ran-dall** [comment]
@EliverLara Hey brother, good to hear from you.

(My system is supposed to be Gentoo, but I'm a developer with so many projects on GNOME, and I'm one of the GNOME maintainers on Gentoo, you could consider it some cross between Neon, Gentoo, and LFS. I'm always on the latest testing version of GNOME.)

`Linux n7 5.19.4-gentoo`
GNOME: 42.4
X11
NVIDIA 1080ti / UHD 630
