### ISSUE TITLE
Broken Dock

### ISSUE THREAD

**Issue by Im-Kal** [dracula/gtk#211]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![image](https://user-images.githubusercontent.com/69103102/184499405-c5040b82-6485-49b1-a419-ee3c9d3cfaf6.png)

Pop OS, have re-installed EVERYTHING

**Comment by Im-Kal** [comment]
Not using COSMIC dock.

**Comment by EliverLara** [comment]
Llease take a look to https://github.com/dracula/gtk/issues/124
