### ISSUE TITLE
Text on Menu No Contrast

### ISSUE THREAD

**Issue by SupianIDz** [dracula/gtk#213]
The text on the application menu almost blends into the background..

Zorin OS 16.1 Pro

![Screenshot from 2022-08-24 01-14-49](https://user-images.githubusercontent.com/37969970/186223035-591e15f8-1c34-4c81-bc18-77111c778c65.png)
![Screenshot from 2022-08-24 01-15-18](https://user-images.githubusercontent.com/37969970/186223041-8b827159-f8ec-4a53-a6f9-4552f2023623.png)

**Comment by EliverLara** [comment]
Hi, I've tested the theme in a clean installation of Zorin OS (No pro version) and it looks fine to me:

![Captura de pantalla de 2022-09-09 14-11-09](https://user-images.githubusercontent.com/9838260/189426646-a31028b9-1e01-4e3b-891d-2c32bb45d72e.png)

Could you please try using the version for newest `gnome-shell` versions [as described here](https://github.com/dracula/gtk/issues/124#issuecomment-875036340)
