### ISSUE TITLE
Ubuntu 22.04 - Firefox and some other apps broken after changing folder colour in settings

### ISSUE THREAD

**Issue by malcolmturnbull** [dracula/gtk#215]
Per above, I had Dracula working on a non-snap install of Firefox, so that the close / minimise / maximise icons were consistent with the  theme. 
![image](https://user-images.githubusercontent.com/8454281/188267607-e77b1255-ae26-471a-9b2a-bef2f06f6b0f.png)

I stupidly tried to select a folder colour using System Settings - Appearance after having no luck using Folder-Color with Nautilus. This changed my theme back to the system default, and changed Firefox's theme at the time.

I have uninstalled and reinstalled Firefox, ensured it is not a Snap installation, installed using the binary from their website, and have had no joy getting the app to recognise Dracula as the GTK Theme. 

Any hints or recommendations would be very much welcome!

**Comment by malcolmturnbull** [comment]
I was able to achieve a partial fix by: 

1. Reapplying the theme using `gsettings set org.gnome.desktop.interface gtk-theme Dracula-shell-pink-accent-v40`
2. Using `sudo flatpak override --env=GTK_THEME=Dracula-pink-accent-slim` to apply selected theme to Flatpaks.
3. In GNOME Tweaks, my Shell is selected as `Dracula-shell-pink-accent-v40` & Legacy as `Dracula-pink-accent-slim`

This seems to have applied the application to the Flatpak version of Firefox but not the Deb installation or a deb installation of Librewolf, which looks like this: 
![image](https://user-images.githubusercontent.com/8454281/188288786-a18fd9ae-cae2-433c-aeca-c7d54f2cf9ed.png)

The other area that seems to have forgotten any theming are Extension settings - Snap Apps had never worked but Caffeine, for e.g., looks like this when it previously showed a dark theme: 
![image](https://user-images.githubusercontent.com/8454281/188288861-bc984469-48e3-459d-a79d-3b94f29d9f74.png)

**Comment by malcolmturnbull** [comment]
For _Gnome Extensions & Associated Prompts_, I used the build referred to in #200 
by pulling and running `make`. Simple! 

This did not fix: 
- Ubuntu Software
- Librewolf Deb
- Firefox Deb

**Comment by EliverLara** [comment]
Hi, I've tested the theme in a clean installation of ubuntu 22.04 and it looks good for non-snap applications (compared below):

![Captura de pantalla de 2022-09-09 15-35-31](https://user-images.githubusercontent.com/9838260/189439231-bb60f2d8-1765-4271-a2f8-f514c0816c55.png)


 Are you sure that you completely remove the snap version of those applications?
