### ISSUE TITLE
[BUG] Border around cosmic dock Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by sinful-mads** [dracula/gtk#216]
**Describe the bug**
A dark border has appeared around the dock of my Pop!_OS distro :)

**To Reproduce**
Make the dock visible by either hovering the curser down at the bottom of the UI or have it permanently visible

**Expected behavior**
I have run into an issue where there is a visible border around the Cosmic Dock in Pop!_OS 22.04 LTS GTK 4 :) I have tried searching for the border settings to the dock in the css files of the gtk-4.0 theme folder, but to no avail.. Which css setting should I look at to achieve the change and remove the border? :)

**Screenshots**
![image](https://user-images.githubusercontent.com/105631567/188455824-a13d2bfc-4012-447b-a18d-2a6a66c39484.png)
![image](https://user-images.githubusercontent.com/105631567/188455849-97ce7f70-e00d-4bfd-bdab-c3e9ef74c5d7.png)

**Additional context**
Full extension list
![image](https://user-images.githubusercontent.com/105631567/188455942-9512283b-7e08-41b2-b24a-d07c648002c3.png)

**Comment by Its-Juice** [comment]
here i am again. still happens and it is very annoying

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version, please take a look to https://github.com/dracula/gtk/issues/124

| wrong shell version      | Correct version |
| ----------- | ----------- |
| ![Captura de pantalla de 2022-09-09 13-52-10](https://user-images.githubusercontent.com/9838260/189424336-0f6558d5-3b95-4d30-8bf4-a7bd3a02212b.png) | ![Captura de pantalla de 2022-09-09 13-53-35](https://user-images.githubusercontent.com/9838260/189424390-8a2e75a2-7f81-44d3-b013-76e8238bc2d8.png) |

**Comment by sinful-mads** [comment]
> Hi, it seems you're using the wrong shell theme version, please take a look to #124
> wrong shell version

How do I check which version I am on and where do I find the correct one?

**Comment by sinful-mads** [comment]
> Hi, it seems you're using the wrong shell theme version, please take a look to #124
> wrong shell version 	Correct version

I followed the steps described here. Did not fix the issue. System info shown here.
![system info](https://user-images.githubusercontent.com/105631567/189599508-2cb4aaa7-06e7-45c5-846d-6f57bdbc77e5.png)
![tweak settings](https://user-images.githubusercontent.com/105631567/189599621-a543b059-aab7-4eab-9c94-dfac64841a43.png)

**Comment by Its-Juice** [comment]
> Hi, it seems you're using the wrong shell theme version, please take a look to #124
> wrong shell version 	Correct version
Thanks i had no idea lol. Now it works perfectly. Sorry for being 15 days late lol

**Comment by sinful-mads** [comment]
> > Hi, it seems you're using the wrong shell theme version, please take a look to #124
> > wrong shell version 	Correct version

> > Thanks i had no idea lol. Now it works perfectly. Sorry for being 15 days late lol

Can you tell me exactly what you did? Because It failed to fix my issue

**Comment by cn-hew** [comment]
> > Hi, it seems you're using the wrong shell theme version, please take a look to #124
> > wrong shell version 	Correct version
> 
> I followed the steps described here. Did not fix the issue. System info shown here. ![system info](https://user-images.githubusercontent.com/105631567/189599508-2cb4aaa7-06e7-45c5-846d-6f57bdbc77e5.png) ![tweak settings](https://user-images.githubusercontent.com/105631567/189599621-a543b059-aab7-4eab-9c94-dfac64841a43.png)

Hi bro~,
 I have the same system version as yours, but there are only two options of light and dark in my appearance panel, and I have installed the user-themes extension
