### ISSUE TITLE
[BUG] White menus on PopOS 22.04 LTS

### ISSUE THREAD

**Issue by stefan-tcaciuc-99** [dracula/gtk#220]
**Describe the bug**
I am getting white Menus while using Dracula shell v40.Changing shell to a non v40 fixes this issue however it then breaks the dock. Also changing the name to Dracula-dark doesn't not fix the issue.
<p float="left">
<img src="https://user-images.githubusercontent.com/87198183/197417983-f4f9fdbb-e483-476f-8049-ef1998d41b81.png" width=40% height=50%>
<img src="https://user-images.githubusercontent.com/87198183/197417991-0e61de7b-d6b7-49d0-8621-e8c67310afe0.png" width=40% height=50%>
<img src="https://user-images.githubusercontent.com/87198183/197417978-35894438-4289-4431-aa55-713383f9cc69.png" width=40% height=50%>
</p>

![image](https://user-images.githubusercontent.com/87198183/197418043-04e03295-38f2-4bc0-9a38-7e419b1f5b14.png)

**Comment by EliverLara** [comment]
Please try using the latest version releasen on [gnome-look](https://www.pling.com/p/1687249/)
