### ISSUE TITLE
[BUG] Mismatched color themes on ubuntu 22.10

### ISSUE THREAD

**Issue by sumitst05** [dracula/gtk#221]
**Describe the bug**
Recently upgraded to **Ubuntu 22.10**. After the upgrade, the system menu colors seem to be too bright.
Also the theme is not working on title bars of system applications like Files, Settings, GNOME Software, Ubuntu Software, etc.
_(PS: The theme never worked on Ubuntu Software for Ubuntu 22.04 LTS but it used to work on GNOME Software before)_

**To Reproduce**
1. Go to the top right of the gnome-panel
2. Click on system menu
3. See error
4. Open any system application (Eg: Settings, Files, Ubuntu Software, GNOME Software, etc)
5. See the title bar of above or similar applications

**Expected behavior**
1. On Ubuntu 22.04 LTS, the color theme was the assigned color. After the upgrade to 22.10, the system menu has changed and probably because of that the color theme of the panels opened by its buttons have a white color theme.
2. The theme does not work on the system applications (Theme doesn't work entirely on Ubuntu Software).

**Screenshots**
![197383412-2731ab98-c7d2-4cf2-af91-b4e871f3ca7b](https://user-images.githubusercontent.com/106669732/197567823-74c3f1a8-2db0-4005-84d4-bc739e0dcaf3.png)
![197383410-05ce61cf-45f5-4c90-ad8d-af81c0e17ce7](https://user-images.githubusercontent.com/106669732/197567856-ce4ee937-3098-4551-8fd2-4abb3a18895f.png)
![Screenshot from 2022-10-24 21-09-49](https://user-images.githubusercontent.com/106669732/197567881-d6902b5b-5b05-4297-8342-75b905a22a92.png)

**Comment by EliverLara** [comment]
The gnome shell issue was fixed with 3a9f544855f163dc12f84a2bc0f103007128a679

For the other issue please make sure they're not snap applications, if they're not snap [this](https://github.com/odziom91/libadwaita-theme-changer) should work as a temporary solution.
