### ISSUE TITLE
Not changing nautilus colors

### ISSUE THREAD

**Issue by NicTanghe** [dracula/gtk#222]
Not changing nautilus colors

i apply the icon theme and color theme.

Only the colour in lx apearance changes. nautilus keeps using the od theme.

**Comment by EliverLara** [comment]
Could you please provide more info about your OS ?

**Comment by ricantech** [comment]
Hi @EliverLara 

I'm getting the same issue. 
Here's neofetch details. In case you would need something else, please let me know!

![image](https://user-images.githubusercontent.com/5075491/203000419-3684c483-db3c-459f-8d28-37e3874b008b.png)

**Comment by NicTanghe** [comment]
Hello I`m on RHEL 8,
I have since fixed this,

I don't remember what fixed it.
I think it was changing the name of the extracted folder to the name of the theme that fixed it.

**Comment by NicTanghe** [comment]
anny way to transfer owmership to ricantech ?

**Comment by i-Gondor** [comment]
Also experiencing this - have renamed the theme folder to no avail.

![image](https://user-images.githubusercontent.com/4557194/204397157-713b2286-9df7-477a-90c2-7c5813b34eb5.png)

**Comment by EliverLara** [comment]
@i-Gondor try using [this](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by i-Gondor** [comment]
> @i-Gondor try using [this](https://github.com/odziom91/libadwaita-theme-changer)

Thanks, this resolved the issue for me.

**Comment by NicTanghe** [comment]
Im on RHEL-9 now.
Sorry for not replying i wil try fix in a sec

**Comment by NicTanghe** [comment]
can`t run the script becouse RHEL is stuck on pythin 3.9
