### ISSUE TITLE
[FEATURE] Theme doesn't work well the latest version of Gnome shell (43)

### ISSUE THREAD

**Issue by kzzexpro** [dracula/gtk#223]
**Certain UI elements look weird**
Notably the system toggles menu looks incorrect 

![image](https://user-images.githubusercontent.com/117155190/199189000-6cb64e10-d1f0-40e2-a15d-e6d61804efdf.png)

**Comment by EliverLara** [comment]
Fixed with 3a9f544855f163dc12f84a2bc0f103007128a679
