### ISSUE TITLE
small jerking movements in quick settings menu

### ISSUE THREAD

**Issue by dinojr** [dracula/gtk#226]
The quick settings menu jerks a little bit each time the mouse hovers over one of its elements. See the attached screencast.
[Capture vidéo du 2022-11-28 15-29-15.webm](https://user-images.githubusercontent.com/2698065/204302898-402a98e0-9f61-4e9b-87ae-cd2fc9e36238.webm)

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version, please take a look to https://github.com/dracula/gtk/issues/124
