### ISSUE TITLE
more polish notification for xubuntu (xfce4-notifyd i think) and make logout dialog (xfce4-session i think) more visible when navigate using keyboard

### ISSUE THREAD

**Issue by denikris** [dracula/gtk#23]
![xfce4-notifyd](https://user-images.githubusercontent.com/16707606/61219146-cca94600-a73d-11e9-9305-0f756a375207.png)

this is screenshot of **Ant-Dracula slim** version when i change brightness using laptop keyboard, maybe it's need more polish, and _logout session_ that i access from _whisker menu_, its navigation not visible when move it using keyboard.

also can you add **how to change color** in **read me** so other user that want to change color don't have to search in closed issues? thank you :-)

**Comment by EliverLara** [comment]
Hi, Could you tell me what's wrong with the current notification style? and also, Do you talk about the session dialog shown below? if so, it shows a dotted border when navigating using keyboard

![Captura de pantalla de 2019-07-16 11-58-58](https://user-images.githubusercontent.com/9838260/61314373-19366500-a7c2-11e9-990e-d990b45209b4.png)

**Comment by denikris** [comment]
notification is ok actually, maybe just make it less rounded for volume/brightness stick/bar

session dialog in my current version had no dotted in it, also there is pink (i've changed to purple) border outside session dialog

**Comment by EliverLara** [comment]
Thank you so much for the feedback! Could you tell me what is your xfce version please ?

**Comment by denikris** [comment]
it's 4.12.x on xubuntu 18.04.x
