### ISSUE TITLE
New release and/or nightly builds?

### ISSUE THREAD

**Issue by errantepiphany** [dracula/gtk#232]
It looks like the last release (3.0.0) was over a year ago now (Dec 30, 2021), and I see that in recent weeks there have been changes for Gnome 43. Can a new release please be cut, and/or can nightly builds please be put into place so that people can download the latest tar.xz file? There is no Makefile or build instructions, so I don't know how to create the archives myself. Thank you!

**Comment by EliverLara** [comment]
Sorry for the very late response, a new version was just released.

**Comment by errantepiphany** [comment]
Thank you! Closing this issue.
https://github.com/dracula/gtk/releases/tag/v4.0.0
