### ISSUE TITLE
Title Bar is white after install[BUG]

### ISSUE THREAD

**Issue by Mandraulic** [dracula/gtk#234]
![image](https://user-images.githubusercontent.com/50908661/212591201-ff3eed49-b594-4458-b399-5dd266a61462.png)

I downloaded the theme via https://draculatheme.com/gtk. I was expecting a dark title bar, and now I don't know how to change it back.

**Comment by EliverLara** [comment]
Please meke sure the package you're using is up to date by using the git version or downloading the .tar files [directly from gnome-look](https://www.pling.com/p/1687249/)

**Comment by CBroz1** [comment]
I may be experiencing the same issue in Pop_OS. 

Steps to recreate:
1. Fresh install of Pop_OS
2. Download and install `.zip` following instructions at https://draculatheme.com/gtk

To more readily manage `gsettings`, I also use [GNOME tweaks](https://github.com/GNOME/gnome-tweaks)

In my case, setting the application theme to the provided `gtk-master` resets the underlying OS from dark mode to light mode. Could it be the case that some component of the UI is not covered by this dracula theme, and my OS defaults to light mode in this case?
