### ISSUE TITLE
[BUG] Does not work with gtk-4 legacy apps

### ISSUE THREAD

**Issue by schwrzstrbn** [dracula/gtk#235]
**Describe the bug**
Dracula gtk theme does not work with gnome extensions.

**To Reproduce**
1. Follow all the installation procedure.
2. Set Dracula as theme and install gnome extensions.
3. open extensions...
4. See that the theme does not covers the extensions app

**Expected behavior**
It should've changed the theme for the extensions app but it did not.

**Screenshots**
![image](https://user-images.githubusercontent.com/45195351/216758698-f9d28d40-6992-4011-b70a-8eaf972e47e8.png)

**Additional context**
Works in any other apps.

**Comment by hlafaille** [comment]
I have the same issue here. Arch Linux, doesn't seem to change the theme for any GTK4 app. File manager and Gnome Terminal are the Adwaita theme still.

**Comment by EliverLara** [comment]
Please try using [this](https://github.com/odziom91/libadwaita-theme-changer), that script should fix this issue.
