### ISSUE TITLE
[BUG] No longer able to set panel height lower than 32 in Plasma 5.27.

### ISSUE THREAD

**Issue by DemonicSavage** [dracula/gtk#236]
**Describe the bug**
Due to a change in Plasma 5.27 (https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/2329/diffs#a59fc6b4fc8c9491e223a39a5c49d288286e16f0_1535_1555), themes now have a minimum panel thickness. Earlier, we could have a panel of thickness 20 with the Dracula theme. Now, it only goes as low as 32, making the panels too thick.

**To Reproduce**
1. Right click on panel
2. "Enter edit mode"
3. Change "panel height" to a number lower than 32

**Expected behavior**
If you enter e.g. 24, the panel should be 24 pixels tall. Instead, it goes back to being 32 pixels tall.

**Comment by EliverLara** [comment]
That was an issue of KDE directly, but they've already fixed it :)
