### ISSUE TITLE
[BUG] they have no window control buttons.

### ISSUE THREAD

**Issue by pipetoroc** [dracula/gtk#237]
**Describe the bug**
when I apply this theme for GTK4 apps (by moving gtk.css and gtk-dark.css into gtk-4.0 directory), they have no window control buttons. This bug is in many of your themes.

**Screenshots**
![Screenshot from 2023-02-25 14-48-30](https://user-images.githubusercontent.com/94933663/221371883-c57d0b2f-6c97-4e3a-88b9-fe087cf73ab4.png)

**Comment by EliverLara** [comment]
Hi, you must also copy the assets folder, please try using [this script](https://github.com/odziom91/libadwaita-theme-changer)
