### ISSUE TITLE
File explorer not using theme - web browser

### ISSUE THREAD

**Issue by JaminMartin** [dracula/gtk#239]
**Describe the bug**
When saving a file from browsers (all I have noticed this on)  the file explorer is not in the gtk-master / shell theme

**To Reproduce**
Steps to reproduce the behaviour:

1. Ubuntu theme set to light (changing the theme automatically sets it to light)
2. follow instructions for installing themes as per the website i.e install themes in /usr/share/themes
3. all windows behave normally until pc restarts (the dark mode is preserved for the browser file explorer windows), after restart file explorer windows from the browser are in a light theme. (see screenshots)

**Expected behaviour**
All windows would adhere to the theme
**Screenshots**
![Screenshot from 2023-03-16 20-49-35](https://user-images.githubusercontent.com/33270052/225551828-13c75501-91e1-425a-b444-45cfddd5da9f.png)
![Screenshot from 2023-03-16 20-50-29](https://user-images.githubusercontent.com/33270052/225551837-c927df92-7a1f-4482-87cc-9a280a9cd88e.png)
![Screenshot from 2023-03-16 20-54-28](https://user-images.githubusercontent.com/33270052/225551841-284493d2-02ca-4489-a8e5-792eff865938.png)

**Additional context**
Sorry if this is a simple fix! I am relatively new to themes / gtk on Linux. 

Thanks!

**Comment by ArgemiroLucena** [comment]
To use GTK4 themes in Gnome 43+ we need to copy the contents of the GTK4 folder inside the theme folder to "~/.config/gtk-4.0". This will work in new GTK4 applications. However, the icon for maximizing, minimizing and closing windows does not appear in nautilus and other applications. The Tokyonight theme is 100% working on the new system, but I love the Dracula theme. I'm waiting for the correction <3

Working Theme: Tokyonight
![image](https://user-images.githubusercontent.com/90817440/236652847-eeb70e2c-fa3d-4f63-ac44-419e1c24a0e7.png)

Dracula Theme with bug
![image](https://user-images.githubusercontent.com/90817440/236652963-dcf2d09b-608e-486c-a0c8-c77ae45c0893.png)

**Comment by yns0100** [comment]
@ArgemiroLucena, you can see here #243 how to fix button bug

**Comment by EliverLara** [comment]
To fully theme gtk4 apps  [this script](https://github.com/odziom91/libadwaita-theme-changer) works fine
