### ISSUE TITLE
[SOLVED]No window buttons on GTK4 apps

### ISSUE THREAD

**Issue by tdtooke** [dracula/gtk#243]
No minimize, maximize, close buttons on GTK 4 apps line Nautilus or Settings in Gnome 44.  I did link the gtk4 theme into ~/.config, just so you know.  This very well may be a Gnome bug and not anything specific to your theme.  In order to not have a weird haloish outline around some apps I have to use XWAYLAND_NO_GLAMOR=1 as of Gnome 44.  That wasn't a problem when I was on Gnome 43.5 so this problem might be due to new bugs introduced in the Gnome upgrade.  But this is by far a superior Dracula theme so I hope either Gnome or you figure this out.

**Comment by yns0100** [comment]
The issue for that is the reference for the ../assets Folder in the gtk.css file, because you moved it into gtk-4.0 folder. An easy fix is to copy assets into .config or just correct the reference in the gtk.css file

**Comment by tdtooke** [comment]
Thank You!!!

**Comment by bridnour** [comment]
I will add that I encountered the same issue with GTK4 apps and that correcting the reference fixes this issue.  I've yet to notice any other issues with this theme.

**Comment by Cornul11** [comment]
You may use this tool I've created to apply it to GTK4 windows as well: [GTK4ThemeAdapter](https://github.com/Cornul11/GTK4ThemeAdapter)

**Comment by MinhPhuoc2703** [comment]
> You may use this tool I've created to apply it to GTK4 windows as well: [GTK4ThemeAdapter](https://github.com/Cornul11/GTK4ThemeAdapter)

nice tool tks u so much

**Comment by EliverLara** [comment]
For newer versions of gnome using libadwaita it's highly recommended to use [this script](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by Cornul11** [comment]
> For newer versions of gnome using libadwaita it's highly recommended to use [this script](https://github.com/odziom91/libadwaita-theme-changer)

The tool I developed does the same, but makes sure to link the correct paths for both system-wide installations of the theme, and user installations. Also, it allows resetting to default settings.
