### ISSUE TITLE
GNOME Power menu missing styling.

### ISSUE THREAD

**Issue by stephanlamoureux** [dracula/gtk#245]
**Describe the bug**

The notification menu in GNOME 44 is missing styling.

**Expected behavior**

The button style should match the sliders.

**Screenshots**

![Screenshot from 2023-06-03 19-25-37](https://github.com/dracula/gtk/assets/16889593/79914f19-7869-44d1-b9ba-2f30d17a8dc7)

**Additional context**

GNOME 44.1 | Fedora 38 | GTK 4.10.3.3

**Comment by EliverLara** [comment]
Hi, it seems you're using the wrong shell theme version, please take a look to https://github.com/dracula/gtk/issues/124

**Comment by stephanlamoureux** [comment]
Welp, I fried my motherboard so I won't be able to tell if this was the cause. I did copy the files from the gtk4 dir of the theme to the gtk4 dir in GNOME though.  But it looks like I was supposed to copy them elsewhere maybe.

**Comment by RouHim** [comment]
> Hi, it seems you're using the wrong shell theme version, please take a look to #124

Great that also helped me a lot :)
May be worth mention this fix in the README or https://draculatheme.com somewhere, as it seems to be a repetitive issue that people get wrong time and time again.

**Comment by RouHim** [comment]
Couldn't we even discuss whether the delivery of the v40 components should be the standard? All major distributions are now running far over 40.
