### ISSUE TITLE
[BUG] Task manager indicators are invisible in KDE

### ISSUE THREAD

**Issue by sandorex** [dracula/gtk#248]
**Describe the bug**
Task manager indicator whether the launcher is running or just pinned is missing

**To Reproduce**
1. Use icon only task manager in a panel
2. Pin two apps
3. Open one of them

**Expected behavior**

It should be visible which app is open, which is not

**Screenshots**

With dracula
![Screenshot_20230716_115205](https://github.com/dracula/gtk/assets/18004075/ea53dd8a-9144-4772-85cc-53ef590e44ef)

With breeze
![Screenshot_20230716_115227](https://github.com/dracula/gtk/assets/18004075/79f51a8b-7ce1-433b-a4a8-b44c4625f26d)

**Additional context**

Plasma Version 5.27.5 on Debian 12

It's all in the `widgets/tasks.svgz`, as i was able to just copy the file from breeze theme and transplant it into dracula

**Comment by EliverLara** [comment]
Thanks for reporting! that issue was fixed with 27baae431e1747d320024b0223c151749593325e
