### ISSUE TITLE
[BUG] Ascent color is not applied to cinnamon calendar (Date of the current day)

### ISSUE THREAD

**Issue by turkishyordle** [dracula/gtk#250]
**Describe the bug**
hello, I've noticed that the dracula theme (purple ascent) doesn't apply to the cinnamon calendar. i own the lastest version downloaded on here : https://www.cinnamon-look.org/p/1687249 .. 
i'am using linux mint 21.2 cinnamon 5.8.4

**To Reproduce**
1. Setup the theme
2. Click on "TIME" on taskbar
3. See that ascent color is not applied on date

**Expected behavior**
you should see the purple colour on the current date
above you can see the difference between dracula purple and dracula pink

**Screenshots**
![1](https://github.com/dracula/gtk/assets/144339573/560e241e-f6a3-4dd1-ab35-40e5ad6d7e14)
![2](https://github.com/dracula/gtk/assets/144339573/4060a550-2104-4849-a014-ca6c4558477b)

Hope it can get resolved ! thanks for making this theme possible.

**Comment by EliverLara** [comment]
Thank you so much for reporting! that was just fixed.
