### ISSUE TITLE
[BUG] Write a suitable title

### ISSUE THREAD

**Issue by Cornul11** [dracula/gtk#251]
First, great job to the maintainers, and thank you for your effort. Here is something I've noticed during my usage of this theme.

**Describe the bug**
On Gnome 44, the `gnome-shell` theme seems outdated, as there are places where things do not look how they should. Moreover, the `System Monitor` icon in the dock seems larger than the others. The same goes for, for example, PyCharm, as seen in the attached screenshot below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the power menu.
2. Open the apps menu.
3. Hover over the dock.

**Expected behaviour**
A consistent look and style. Round icon backgrounds. 

**Screenshots**

Power menu:
![image](https://github.com/dracula/gtk/assets/15735127/e528a2dd-003f-494d-b2dd-94c0ab64f32b)
Dock:
![image](https://github.com/dracula/gtk/assets/15735127/dbe35048-5176-4465-862b-aaab53b9e1ef)
Apps menu:
![image](https://github.com/dracula/gtk/assets/15735127/7460c28f-199a-4c70-aa0d-fbe48a0acde2)

**Comment by EliverLara** [comment]
Could you please try using the latest version [released here](https://www.pling.com/p/1687249/)
