### ISSUE TITLE
[BUG] Active/Inactive indicator is not visible for xfce4-docklike-plugin

### ISSUE THREAD

**Issue by subhadig** [dracula/gtk#252]
**Describe the bug**
The active/inactive indicators for the applications are not visible in the xfce4-docklike-plugin with the Dracula/Dracula-alt-style themes (version: 2023-09-13). I am on Debian 12.

**To Reproduce**
1. Use xfce4-docklike-plugin in xfce panel.
2. Pin a few applications to the dock. Launch a few applications.
3. Notice that the active/inactive indicators are not visible.

**Expected behavior**
The active/inactive indicators should be visible on the application icons on the xfce4-docklike-plugin.

**Screenshots**
![Screenshot_2023-09-24_22-16-02](https://github.com/dracula/gtk/assets/6718975/c1ca2b21-acdc-4374-b430-8a0fc3bf3dc3)

**Additional context**
When using a one-year old version of the same themes, the issue is not present. The issue could be the result of https://github.com/dracula/gtk/commit/6ed4a6dfe6579a409dafbfe48a5e7473eab2a4bc

**Comment by EliverLara** [comment]
Fixed with e3400f7c08f015ceba05d7732951cb6b868e7dcc
