### ISSUE TITLE
Double borders on Ubuntu v22

### ISSUE THREAD

**Issue by YaGRRusso** [dracula/gtk#254]
Im using Dracula theme on Ubuntu v22 and im having a double borders on floating menus, its like one window under another window. I dont know how to fix this

## System
![Captura de tela de 2023-10-26 13-55-42](https://github.com/dracula/gtk/assets/61320909/40d1c1ca-3bab-4e3b-99bc-49ed7e3358ca)

## The Double Borders
![Captura de tela de 2023-10-26 13-56-45](https://github.com/dracula/gtk/assets/61320909/0044a994-4e12-45c3-bde4-a79efaab912b)

## Prints 
![Captura de tela de 2023-10-26 13-55-55](https://github.com/dracula/gtk/assets/61320909/c120973b-ee00-4f46-bb21-6ba3c305c602)
![Captura de tela de 2023-10-26 13-56-11](https://github.com/dracula/gtk/assets/61320909/b16b1a5d-e757-4518-aa41-84057f8fe352)

**Comment by EliverLara** [comment]
Could you please try using the latest version [released here](https://www.pling.com/p/1687249/)

**Comment by YaGRRusso** [comment]
I've download the theme from the [official Dracula website](https://draculatheme.com/gtk), but it's a wrong version
