### ISSUE TITLE
[BUG] Hovering over buttons in Panel's System Menu increases their size

### ISSUE THREAD

**Issue by arpoja** [dracula/gtk#260]
**Describe the bug**
The "System Menu" region of Gnome shell, the button in the top right of the panel has inconsistent button sizes for "normal" buttons and those that a user hovers over with a mouse.

I am on Gnome 45, but have noticed this on earlier versions as well.

**To Reproduce**
1. Open the "System Menu" from the top right "button" of Gnome shell in the Panel
2. Hover over the buttons
3. Buttons with a "->" to access more settings only grow vertically
4. "Full" buttons grow vertically and horizontally
5. Disabling the Dracula theme shows that this issue does not happen with Vanilla Gnome

**Expected behavior**
Hovering over buttons in the "System Menu" does not grow the buttons and the system menu region

**Screenshots**
Did not record cursor, but you can see the action from hovering over the buttons. 
[Screencast from 2023-11-24 18-56-27.webm](https://github.com/dracula/gtk/assets/59693591/04e983b5-ea88-4da3-916f-04d4f4efb03f)

**Comment by EliverLara** [comment]
Hi, it seems you were using the wrong version of gnome-shell, but it was fixed with 107c6e73ca2a47a182ce3c157e8d9c3717616ca3 :)
