### ISSUE TITLE
[BUG] Toggle Switch Stretched in Extension Manager

### ISSUE THREAD

**Issue by Joomsy** [dracula/gtk#263]
When using `gtk-4.0` symlinks under home in order to skin `libadwaita` applications, this causes the switch at the top of the GNOME extension manager to stretch and distort. This may be due to the version of GNOME that I use, as GTK4 is a little funny under 42.9 (Pop_OS!), but I figured this is worth mentioning. It really throws off the feeling of the rest of the application.

![image](https://github.com/dracula/gtk/assets/103767404/fce40376-24bf-4350-94a5-8717e8dbbc95)

**Comment by EliverLara** [comment]
That was fixed with 32ce47c2e9b2f7504490815654b47d670a3fd9ca
