### ISSUE TITLE
Calendar and options menu looks white

### ISSUE THREAD

**Issue by mavi3** [dracula/gtk#265]
![image](https://github.com/dracula/gtk/assets/56947440/2fcef81e-2d30-4390-8adc-570df1640124)

![image](https://github.com/dracula/gtk/assets/56947440/d0120be9-4cc1-4581-b4d3-34d96c53ae9b)

**Comment by agreppin** [comment]
For Ubuntu 22.04.03:
1. install in /usr/share/themes and /usr/share/icons, rename extracted dir as Dracula
2. sudo apt install gnome-shell-extensions
3. open the 'Extensions' app from the Activities menu
4. enable 'User themes'
5. open the 'Tweaks' app
6. select Dracula for Appearence > Themes > Applications, Icons & Shell

![Extensions-app](https://github.com/dracula/gtk/assets/26579013/e9e57324-7cad-4a45-8174-f081b1e1c6a6)
![Tweaks-app](https://github.com/dracula/gtk/assets/26579013/ffeccbde-356b-4b81-98bf-a267427e6faf)
