### ISSUE TITLE
[BUG] GTK-4 apps are missing the close, minimize and maximize buttons on their windows

### ISSUE THREAD

**Issue by mediocretwo** [dracula/gtk#266]
**Describe the bug**
The theme is not applied properly to GTK-4 apps like gnome files, gnome settings etc. The close, minimize and maximize buttons on the windows are missing. Clicking where the buttons are supposed to be still executes the expected button action.

**To Reproduce**
1. Unpack the theme and copy the contents of gtk-4.0 to ~/.config/gtk-4.0
2. Log out and log back in
3. See the theme is applied correctly to GTK 3 apps but the close and maximize window buttons are missing from GTK 4 apps.

**Expected behavior**
The close and maximize window buttons should look the same on GTK 4 apps as they do on GTK 3 apps.

**Screenshots**
Please check the screenshot below, I have opened Gnome file manager and there is no close button. When I click the area where the close button is supposed to be, it still works and the app is closed. I'm using Debian 12 with Gnome on Wayland.

![Screenshot from 2024-02-14 02-32-57](https://github.com/dracula/gtk/assets/43803024/14322c66-3d93-4cf5-ba2e-aca2034897d2)

**Comment by 0xNohaki** [comment]
same problem on two machines running ubuntu 23.10 with gnome on wayland

**Comment by EliverLara** [comment]
Hi, to get it properly working with libadwaita apps it's highly recommended to use [this script](https://github.com/odziom91/libadwaita-theme-changer), or if you prefer doing it manually you must also copy the **`assets`** folder into **`~/.config`**

**Comment by mediocretwo** [comment]
@EliverLara Thank you!
