### ISSUE TITLE
[BUG] Files unfocused border thickness and search box

### ISSUE THREAD

**Issue by VirtualJunky** [dracula/gtk#267]
**Describe the bug**
When browsing files and you click to another window, the unfocused files window has some extra bold borders around "Name | Size | Modified" 

Side question; in the screenshot shown on Github ([here](https://github.com/dracula/gtk/blob/master/screenshot.png)) it shows the search box being a separate color, but screenshots posted on Gnome-look ([here](https://images.pling.com/img/00/00/36/61/48/1687249/dracula.png)) show as I am seeing it, which is correct? Because I would prefer the search box to be a different color, as shown on the Github included screenshot.

**To Reproduce**
1. Go to Files
2. Click off window
3. Extra thick border

**Screenshots**
Focused window:
![Screenshot from 2024-02-27 12-13-31](https://github.com/dracula/gtk/assets/58893241/d096659d-47fb-4464-bf0f-092d6c2a6444)
Unfocused window:
![Screenshot from 2024-02-27 12-13-55](https://github.com/dracula/gtk/assets/58893241/966d7bab-1e42-4f1f-b710-3993c65b44ea)

**Comment by EliverLara** [comment]
Hi. could you please give me more details about your OS, please?

**Comment by VirtualJunky** [comment]
Oh duh! Sorry about that. Pop!_OS, everything is up to date.

![Screenshot from 2024-02-27 13-39-23](https://github.com/dracula/gtk/assets/58893241/b9f718e2-db5c-460e-a68b-e9a08190cebb)

**Comment by EliverLara** [comment]
It was fixed with 9eb561508e481d77f2d39fbb3a6b2949e990aa4f :)
