### ISSUE TITLE
[BUG] Opening Nautilus freezes whole system for a few seconds

### ISSUE THREAD

**Issue by LeonRein** [dracula/gtk#269]
**Describe the bug**
When opening Nautilus, the whole system freezes for a few seconds. 
Journalctl:
nautilus[11628]: Theme parser error: gtk.css:5653:3-9: No property named "height"

**To Reproduce**
Activate Dracula theme for Shell and Legacy Applications in Gnome Tweaks. Open Nautilus. 

**Expected behavior**
No freeze.

**Additional context**
Using Arch with Gnome Desktop

**Comment by EliverLara** [comment]
Thanks for reporting! it was fixed with c21f12be904fe55336397fc80feb1a8c8216dca2
