### ISSUE TITLE
[BUG] GNOME 46 Dash to Panel icons go up and down

### ISSUE THREAD

**Issue by R1D3R175** [dracula/gtk#271]
**Describe the bug**
Initially, the icons appear like this.
![image](https://github.com/dracula/gtk/assets/54753989/f2ffe767-ed89-4962-8ba5-2accb6c2e4b6)
However, when going on an icon, they change state and go up/down again.
![image](https://github.com/dracula/gtk/assets/54753989/401b6723-fcf3-4557-a7f5-2dbfe1f2cd77)
![image](https://github.com/dracula/gtk/assets/54753989/79b12ef8-7c75-4990-aa8b-04e1cdb4b6a4)

**To Reproduce**
1. Be on GNOME 46
2. Install [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) extension 

**Expected behavior**
This is how the icons are supposed to look (using the default theme, Adwaita).
![image](https://github.com/dracula/gtk/assets/54753989/d1509123-f8f9-4dd4-943b-109f61e3ec0f)

**Comment by mnbilgi** [comment]
Dash to panel works correctly for me, but when I install the Dracula theme, I experience the same problem as above.

**Comment by EliverLara** [comment]
Fixed with 5e9a46b7610da0944a8131bbf08487861cae2c46

**Comment by frkabeatz** [comment]
The problem I have is that the theme is only applied to the shell, the rest of the system and the file manager do not change to the Dracula theme
