### ISSUE TITLE
[BUG] Nautilus/Files

### ISSUE THREAD

**Issue by eerdjan-tech** [dracula/gtk#272]
**Describe the bug**
When setting the Dracula GTK theme in Nautilus the top right window decoration is missing. The ability to sort files A-Z etc, is there and usable but hidden as the icon for the drop down menu is missing. Without the Dracula theme this icon appears as a down triangle.

**To Reproduce**
Install and apply Dracula GTK theme.

**Expected behaviour**
For all window decoration drop down menus to be present and clear.

**Screenshots**
###Dracula###
![Screenshot from 2024-04-25 14-34-48](https://github.com/dracula/gtk/assets/141729082/90603e98-0f66-484f-829c-af1f3a360d37)

###Without Dracula###
![Screenshot from 2024-05-03 14-03-58](https://github.com/dracula/gtk/assets/141729082/bd2ad85a-da36-4097-a50c-3d0b1b682088)

**Additional context**
This is present on Debian 12 using Nautilus/Files Version 43.2.

**Comment by EliverLara** [comment]
[This](https://github.com/dracula/gtk/issues/273#issuecomment-2094343554) should fix this issue
