### ISSUE TITLE
[BUG] Theme no apply

### ISSUE THREAD

**Issue by frkabeatz** [dracula/gtk#273]
The problem I have is that the theme is only applied to the shell, the rest of the system and the file manager do not change to the Dracula theme.

I am using Ubuntu 24.04 with Gnome 46. I hope you can help me

![Captura desde 2024-05-04 12-07-59](https://github.com/dracula/gtk/assets/87776927/cc50cbec-3293-4fd3-a532-7caa837cc8bb)

**Comment by EliverLara** [comment]
Hi, please try using [this script](https://github.com/odziom91/libadwaita-theme-changer) in order to fully theming libadwaita apps

**Comment by 9EED** [comment]
> Hi, please try using [this script](https://github.com/odziom91/libadwaita-theme-changer) in order to fully theming libadwaita apps

this worked for me
