### ISSUE TITLE
[BUG] Menu lag with Dracula Kvantum theme in qt6 apps

### ISSUE THREAD

**Issue by Alanon202** [dracula/gtk#274]
**Describe the bug**
A recent qt6 update has been causing strange behaviour in qt6 apps with extremely laggy submenus and right-click menus. 

This also makes selection menus (like the theme selector dropdown in Kvantum Manager) downright unusable as they dissapear too quickly to click on anything.

Changing the Kvantum theme to something other than Dracula solves the issue. After doing some research I think it’s the same bug as [this one](https://github.com/EliverLara/Sweet/issues/264) in Sweet that @EliverLara fixed a couple weeks back, and indeed the latest Sweet kvantum theme doesn’t exhibit this behaviour for me.

**To Reproduce**
1. Apply Dracula Kvantum theme
2. Open any qt6 app with submenus like PCManFM-qt, Kvantum Manager, qt6ct...
3. Rightclick or try to use any menu in those apps
4. Try to hover over or scroll the menu entries, and observe the lag
5. Note that the lag is more observable in menus with more than 5 entries, any lower and it might seem like normal.

**Expected behavior**
Near instantenuous response of the menu, fast change of highlighted items, etc.

**Additional context**
I’m using Arch Linux with Openbox and picom, Dracula for GTK and Kvantum theming. I was able to reproduce the same behaviour on an AMD laptop with integrated graphics as well as a PC with Nvidia 1080Ti.

**Comment by EliverLara** [comment]
Thanks for reporting! it was fixed with 41f5c025c09c7c8db6e68f9cd4e9d23b8eeea410
