### ISSUE TITLE
Themes option is not working in Ubuntu 24.04

### ISSUE THREAD

**Issue by MaximilianoRodriguez01** [dracula/gtk#275]
![image](https://github.com/dracula/gtk/assets/166071950/8b954c37-2634-47a3-b9d9-901ec11f2b55)

**Comment by MaximilianoRodriguez01** [comment]
The themes option is not appearing in the menu for changing it at ubuntu 24.04

**Comment by EliverLara** [comment]
Please take a look to [this](https://github.com/dracula/gtk/issues/273#issuecomment-2094343554)
