### ISSUE TITLE
[BUG] Theme doesn't apply to calendar and control panel

### ISSUE THREAD

**Issue by armaanansari121** [dracula/gtk#279]
Description:
The dracula theme doesn't apply on calendar and the control panel on the deskptop. Ubuntu 22.04.4 LTS. I have installed the GTK, gnome-terminal and gedit. Applied it using gnome-tweaks.
 
Reproduce:
Install GTK and apply the theme using given instructions. check the calendar and control panel, they would be in light mode.

Expected behavior:
The calendar and control panel do not get the dracula theme.

![Screenshot from 2024-06-30 17-49-24](https://github.com/dracula/gtk/assets/145029005/73a4013b-d592-4ead-8f83-2993cecb24ca)
![Screenshot from 2024-06-30 17-46-34](https://github.com/dracula/gtk/assets/145029005/941f581e-177c-4664-ae33-5f869ae3ec17)
![Screenshot from 2024-06-30 17-46-40](https://github.com/dracula/gtk/assets/145029005/176acf7d-9690-4f99-8aaf-f8947511f77d)

**Comment by EliverLara** [comment]
Please take a look to this https://github.com/dracula/gtk/issues/265

**Comment by armaanansari121** [comment]
Thankyou so Much! It works
