### ISSUE TITLE
I cant use gtk theme in ubuntu 24.04

### ISSUE THREAD

**Issue by longsangphap** [dracula/gtk#280]
org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/24 of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/32 of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/16@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/22@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/24@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/32@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.396: Theme directory actions/symbolic of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/24 of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/32 of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/16@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/22@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/24@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/32@2x of theme Dracula has no size field
(org.gnome.Nautilus:8691): Gtk-WARNING **: 21:39:58.531: Theme directory actions/symbolic of theme Dracula has no size field

This warning when i use nautilus -q to active theme for file manager

**Comment by EliverLara** [comment]
That's an issue with your icon theme, it's not gtk related
