### ISSUE TITLE
folder windows (nautilus) do not change

### ISSUE THREAD

**Issue by jhoni146** [dracula/gtk#281]
The theme in the folders does not change, I still get the default one, I am on Ubuntu 24 with Gnome 46

**Comment by WastedFreeTime** [comment]
I think its because Nautilus uses GTK4 which is currently not supported. Could be wrong

**Comment by EliverLara** [comment]
Hi, please take a look to this https://github.com/dracula/gtk/issues/273#issuecomment-2094343554
