### ISSUE TITLE
[BUG] Latest commit for kvantum that fixes drop down menus breaks UI

### ISSUE THREAD

**Issue by TheKamboy** [dracula/gtk#283]
**Describe the bug**
With the latest commit to fix lag in drop down menus, it broke ui elements to where kvantum uses default graphics for buttons and other ui elements (which can make certain things hard to see, like the storage bar in the screenshot below)

**To Reproduce**
1. [Apply the files from this commit](https://github.com/dracula/gtk/commit/41f5c025c09c7c8db6e68f9cd4e9d23b8eeea410)
2. Open any application that uses kvantum as a theme.

**Expected behavior**
Kvantum themes should use the UI elements in its config.

**Screenshots**
![image](https://github.com/user-attachments/assets/daa6cc3c-f71d-46f1-9bf9-583281e3103f)

**Additional context**
I use the [Hyde config](https://github.com/prasanthrangan/hyprdots) for Hyprland.

**Comment by EliverLara** [comment]
Hi, Could you try downloading directly from the [kde-store](https://www.pling.com/p/1370681/)? please

**Comment by TheKamboy** [comment]
> Hi, Could you try downloading directly from the [kde-store](https://www.pling.com/p/1370681/)? please

I don't use kde. I use hyprland.
