### ISSUE TITLE
Height problem for buttons in "Starting Applications"

### ISSUE THREAD

**Issue by pierrepas** [dracula/gtk#284]
**Describe the bug**
1. Apply "Dracula" theme for applications in cinnamon 6.2.9
2. Go to "Starting applications" menu
3. See that the toggle-switch green buttons are too tall 
4. They look OK in other menus so it's not a big deal, excellent theme by the way

**Comment by pierrepas** [comment]
![dracula_bug_démarrage](https://github.com/user-attachments/assets/1666fdcb-b142-4345-97ce-f197ac8f621f)

**Comment by EliverLara** [comment]
That was fixed with 32ce47c2e9b2f7504490815654b47d670a3fd9ca :)
