### ISSUE TITLE
heme Changes Not Applying correctly on Ubuntu V24

### ISSUE THREAD

**Issue by ElianTrem** [dracula/gtk#285]
I have encountered an issue where theme changes applied through GNOME Tweaks are not affecting as expected

Steps to Reproduce:

    Install a GTK Dracula theme.
    Apply the theme using GNOME Tweaks.
    Observe that the theme changes are applied to legacy applications but not to applications like the file explorer and web browsers.

Expected Behavior:

The applied theme should work

Actual Behavior:

The theme changes are only visible in terminal and shell. Others applications, such as the file explorer and web browsers, do not reflect the applied theme.

Additional Information:

    I followed the installation instructions provided on the official theme website.
    The issue persists despite ensuring that the GTK4 theme is correctly installed and configured.
    GNOME Shell is up-to-date.
    OS: Ubuntu V24

**Comment by EliverLara** [comment]
Hi, please take a look to [this](https://github.com/dracula/gtk/issues/273#issuecomment-2094343554)
