### ISSUE TITLE
[BUG] Theme is not being applied to all windows on LMDE6

### ISSUE THREAD

**Issue by imgustavo** [dracula/gtk#286]
**Describe the bug**
The theme should be applied to all windows on the system. But some of them are being skipped. Like the one in the screenshot below. Its not many of them, but i can find maybe, around 10% of the windows are not being applied by the theme

**To Reproduce**
1. Go to 'Update Manager'
2. Click on 'Download'

**Screenshots**
[](https://i.imgur.com/FpdJLvJ.png
)
**Additional context**
Im using Linux Mint, Debian Edition 6 (LMDE6), Gnome 43

**Comment by EliverLara** [comment]
Hi, please take a look to [this](https://github.com/dracula/gtk/issues/140)

**Comment by imgustavo** [comment]
> Hi, please take a look to [this](https://github.com/dracula/gtk/issues/140)

Thanks sir, this solved the problem. I love your theme, im using it for about 3 or 4 years now i think
