### ISSUE TITLE
[FEATURE] Please! Add hdpi support for xfwm4

### ISSUE THREAD

**Issue by 237dmitry** [dracula/gtk#290]
This is not applicable at all on xfce at 2560x1600. Very narrow disproportionate window titles.

**Comment by EliverLara** [comment]
Hi, COuld you provide a screenshot please?

**Comment by EliverLara** [comment]
One more question; Those applications header in your screenshot are themed by Xfwm4 theme or GTk?

**Comment by 237dmitry** [comment]
> One more question; Those applications header in your screenshot are themed by Xfwm4 theme or GTk?

GTK, I think:

```
$ xfconf-query -c xsettings -p /Net/ThemeName
Dracula

$ xfconf-query -c xfwm4 -p /general/theme
Dracula
```

**Comment by 237dmitry** [comment]
But I am not entirely sure. For example, then I use some themes made by vinceliuice I replace xfwm4 directory with xfwm4-hdpi

https://github.com/vinceliuice/Lavanda-gtk-theme/tree/main/src/assets/xfwm4/assets-Sea-hdpi

**Comment by EliverLara** [comment]
I see now, thanks for the information!.

**Comment by 237dmitry** [comment]
I just tried the nordic themes (darker and Polar) and they work great with hdpi. Thanks a lot!

**Comment by 237dmitry** [comment]
Tested Dracula and it also great on hdpi. So I close feature request. Thank you very much!
