### ISSUE TITLE
Dracula theme not changing everything to dracula type

### ISSUE THREAD

**Issue by Na3ar-17** [dracula/gtk#292]
I've installed theme and icons, and made everything like in the docs,but theme not changing everything,and some icons doesn't work
![Screenshot from 2024-10-16 19-47-22](https://github.com/user-attachments/assets/38ff5100-5684-4009-abaf-763b1e8c52f0)
![Screenshot from 2024-10-16 19-48-07](https://github.com/user-attachments/assets/5a9c0e19-1152-42f4-b0eb-3f5f4ff267b7)

**Comment by EliverLara** [comment]
Hi, did you do this step?

> **For the latest versions of Gnome using Gtk4(libadwaita) some extra steps should be done in order to get it working properly, you could do it in two ways:**

> 1.- Manual way
  > - Copy the `assets` folder to the `~/.config` directory
  > - Copy the `gtk-4.0/gtk.css` and `gtk-4.0/gtk-dark.css` files to `~/.config/gtk-4.0/`

> 2.- Using [this script](https://github.com/odziom91/libadwaita-theme-changer) which will copy the needed folders to the right directories

The icon theme is not part of the `dracula-gtk` project so I'm not the mantainer but it looks like the icon set isn't completed, to fix that you could try with another icon theme like [this](https://github.com/m4thewz/dracula-icons)

**Comment by Na3ar-17** [comment]
> Hi, did you do this step?
> 
> > **For the latest versions of Gnome using Gtk4(libadwaita) some extra steps should be done in order to get it working properly, you could do it in two ways:**
> 
> > 1.- Manual way
> > 
> > * Copy the `assets` folder to the `~/.config` directory
> > * Copy the `gtk-4.0/gtk.css` and `gtk-4.0/gtk-dark.css` files to `~/.config/gtk-4.0/`
> 
> > 2.- Using [this script](https://github.com/odziom91/libadwaita-theme-changer) which will copy the needed folders to the right directories
> 
> The icon theme is not part of the `dracula-gtk` project so I'm not the mantainer but it looks like the icon set isn't completed, to fix that you could try with another icon theme like [this](https://github.com/m4thewz/dracula-icons)

Now it works, thank you 🤝
