### ISSUE TITLE
Issue with Firefox colors being affected, reflecting the same color background with same color text.

### ISSUE THREAD

**Issue by eman1369** [dracula/gtk#4]
Hi I recently installed the Ant Dracula theme on Ubuntu 18.04 LTS and after adding it in some cases of some websites in Firefox the text either read or to write are the same color. I can attach some examples. Other than that I love the theme. Good work!

![screenshot from 2018-06-13 06-09-34](https://user-images.githubusercontent.com/39484325/41345076-ab72a072-6ed0-11e8-9483-491fa492630a.png)
![screenshot from 2018-06-13 06-10-57](https://user-images.githubusercontent.com/39484325/41345077-ac8d2626-6ed0-11e8-9773-a75b1f4e5b91.png)

**Comment by bendersteed** [comment]
This is a general problem with firefox. A temporary solution is to set widget.content.gtk-theme-override in about:config in a light theme of your decision, Adwaita:light works fine for example.

**Comment by denikris** [comment]
this issue affect in almost all dark theme, it's firefox problem and already reported in their bugzilla, not the themes, you can install add-ons [Text Contrast for Dark Themes](https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/) or set it in `about:config` like [this](https://askubuntu.com/questions/1034643/how-to-fix-invisible-form-fields-in-firefox-while-using-adwaita-dark-theme-or-a) post in askubuntu
