### ISSUE TITLE
Move to Dracula organization

### ISSUE THREAD

**Issue by zenorocha** [dracula/gtk#40]
Hey @EliverLara, would you like to move this repository to the [Dracula organization](https://github.com/dracula)?

You would continue to be the maintainer and everything else, but we would consider it an official theme and also add a page on draculatheme.com. 

Let me know what you think ;)

**Comment by EliverLara** [comment]
Hi, @zenorocha  that sounds good! I only have some doubts; Will I be able to continue updating the theme in gnome-look? and also, what about licensing? since this repo uses `GPL v3`.

**Comment by zenorocha** [comment]
Yes. You'll continue to update the theme in gnome-look without a problem. We usually use MIT in all repositories there, but if that's a problem I'm ok with using GPL v3.

About the repo name, we usually use just the name of the app, for example: `dracula/visual-studio-code`. Any ideas on how we should name it? `dracula/gnome`?

P.S.: I'm not very familiar Gnome themes, so please forgive me. If we can do something similar to what you did with [Nordic](https://github.com/EliverLara/Nordic) it would be great.

**Comment by EliverLara** [comment]
Hi @zenorocha, I'm sorry for the late response.

About the repo name what about naming it `dracula/gtk` just as the referred issue 


>  If we can do something similar to what you did with Nordic it would be great 

Do you mean  a similar style?

**Comment by zenorocha** [comment]
Awesome, I love that, `dracula/gtk` looks great.

**Comment by EliverLara** [comment]
@zenorocha What are the next steps to join the organization?

**Comment by zenorocha** [comment]
Awesome! I just sent you an invitation to join the `dracula` organization. Once you accept, you can transfer the repository and rename it :)

**Comment by zenorocha** [comment]
It looks amazing 🤩 🤩 🤩 

https://draculatheme.com/gtk

Thanks @EliverLara for transferring and congratulations on such an amazing theme.
