### ISSUE TITLE
Sidebar margin issue

### ISSUE THREAD

**Issue by jd-0001** [dracula/gtk#43]
In Linux Mint 19.3 Cinnamon, there's sidebar spacing issue compared to screenshot shown in README.md

![dracula](https://user-images.githubusercontent.com/47495003/79604103-1ed32980-810b-11ea-84bd-d95841b9347b.png)

I tried tweaking the theme for PR but I am unable to do it.

Can you please also mention how to add margin or padding to this sidebar?

~ Regards

**Comment by EliverLara** [comment]
That is not a sidebar but a treeview so it looks more compact, I will try to add some padding.
