### ISSUE TITLE
Programs in menu are invisible while searching-ubuntu 19.10

### ISSUE THREAD

**Issue by Rocket002** [dracula/gtk#44]

**Comment by EliverLara** [comment]
Could you provide a screenshot, please?

**Comment by Rocket002** [comment]
Yup
Here's before searching:
![before](https://user-images.githubusercontent.com/64071150/81513436-d1706380-9328-11ea-9538-7452d8e3a9cb.png)

And here's after:
![after](https://user-images.githubusercontent.com/64071150/81513438-d59c8100-9328-11ea-9c16-5345123923cf.png)

**Comment by EliverLara** [comment]
Hi, @Rocket002 Does this still persist?
