### ISSUE TITLE
Dark Text in Arc Menu

### ISSUE THREAD

**Issue by hmajid2301** [dracula/gtk#48]
I'm using arc menu version: 46 and the latest version of this theme released on 19/05/2020. The text in the arc menu is dark like you can see in #44 . `Type to search ...`. 

![IMG_20200520_111147](https://user-images.githubusercontent.com/998807/82436928-79ef9780-9a8e-11ea-8bc3-825ca8c656a7.jpg)

**Comment by derevandal** [comment]
![Captura de tela de 2020-05-25 19-41-03](https://user-images.githubusercontent.com/1340508/82846568-e0761a80-9ebf-11ea-9e33-99a865fea7fd.png)
I have almost the same problem in GTK...

**Comment by EliverLara** [comment]
@derevandal it seems that you're using an older version of the theme, please, make sure you have the latest version released [here](https://www.pling.com/p/1099856/).
