### ISSUE TITLE
Inconsistencies between the accents in the QT and GTK variants 

### ISSUE THREAD

**Issue by clintlombard** [dracula/gtk#49]
Thanks for the awesome work! I've finally found a theme that looks great in both Qt and GTK applications.

The only downside is that the GTK theme has the pink accent, whereas the Qt (KDE) themes have grey or purple. I'd be happy with either choice for both, just want a consistent look.

**Comment by emanuelserpa** [comment]
+1

**Comment by EliverLara** [comment]
GTK theme now has purple accent color! and it looks more consistent with KDE themes.

**Comment by clintlombard** [comment]
Awesome! It looks great. Thanks again for the great theme
