### ISSUE TITLE
focused elements hard to read

### ISSUE THREAD

**Issue by yukulele** [dracula/gtk#5]
focused elements [white on pink] have low contrast and are hard to read.

i suggest to change to [black on pink] or [white on "dark-pink"]

**Comment by sumitsahrawat** [comment]
We could use the 'selection' color defined by dracula: https://github.com/dracula/dracula-theme#color-palette

**Comment by EliverLara** [comment]
The accent color has been changed from pink to purple, so, it looks more contrasted now.
