### ISSUE TITLE
Change AUR package to this repo

### ISSUE THREAD

**Issue by Trollwut** [dracula/gtk#51]
Hey folks,

as this has now migrated into the Dracula project, I guess it would be more consistent to change the linked repos behind these two AUR packages to the new repo:

- https://aur.archlinux.org/packages/ant-dracula-gtk-theme
- https://aur.archlinux.org/packages/ant-dracula-theme-git

I already commented both AUR packages. Please correct me if I'm wrong!

**Comment by milouse** [comment]
As these packages are not directly maintained by @EliverLara, I think this issue is not necessary. You already did the right thing by commenting on Aur.

**Comment by SecurityInsanity** [comment]
FWIW: `ant-dracula-gtk-theme` has been updated appropriately.

**Comment by EliverLara** [comment]
@SecurityInsanity great!
