### ISSUE TITLE
Change the accent color or add different versions with different accent colors

### ISSUE THREAD

**Issue by RaphGL** [dracula/gtk#52]
Pink for me and for many(possibly) have too big of a contrast, it makes it unconfortable for me to look at. Sticks out too much. Since some people may prefer the pink version. Why not add different accent colors to it so people can choose which ones better for them? I particularly am in favor of using the comment color(#6272a4) instead.

Here's some examples of purple as the accent color:
![image](https://user-images.githubusercontent.com/28673457/84576216-2117d400-ad9a-11ea-8ad5-b06f6966c4d0.png)
![image](https://user-images.githubusercontent.com/28673457/84576147-aa7ad680-ad99-11ea-8449-c96fa558fde4.png)
![image](https://user-images.githubusercontent.com/28673457/84576206-10fff480-ad9a-11ea-98e9-3206a139c94e.png)

**Comment by TomasRejhons** [comment]
Yes, the pink is so "IN YOUR FACE". Please, we need an alternative :D

**Comment by EliverLara** [comment]
I've just updated accent color from pink to purple, I think it looks better now:

![dracula-gtk](https://user-images.githubusercontent.com/9838260/85209483-0c898d80-b2fe-11ea-8836-ebf507a94e59.png)

**Comment by RaphGL** [comment]
This is great it. Now I can have a consistent theme on my desktop(but I might create a derivative of it in the future). Great work @EliverLara

**Comment by TomasRejhons** [comment]
Now it's perfect
