### ISSUE TITLE
Ubunto 20 not apply the Drakula theme

### ISSUE THREAD

**Issue by rogeriorioli** [dracula/gtk#54]
I tried to install on ubuntu 20 but it is with the light theme and does not apply the Drakula theme

**Comment by EliverLara** [comment]
Hi, did you extract the theme folder under  `~/.themes`? and how are you applying the theme? are you using a specific tweak-tool for that?

**Comment by rogeriorioli** [comment]
yes i do extrat in theme folder ~/.themes

**Comment by rogeriorioli** [comment]
start from terminal

**Comment by rogeriorioli** [comment]
Resolved , i used gnome-tweeks thanx ALL
