### ISSUE TITLE
specify background color for xfce panel 4.14

### ISSUE THREAD

**Issue by denikris** [dracula/gtk#55]
i use xubuntu 20.04 and this theme doesn't make xfce4-dockbarx-plugin blend with panel color
![blend with panel](https://user-images.githubusercontent.com/16707606/85551666-6a92d980-b64c-11ea-8eaf-e678c2701c60.png)
this is image comparison of dracula(top) and greybird(bottom).

as **M7Z** said in [this](https://github.com/HugLifeTiZ/xfce4-dockbarx-plugin/issues/38) comment, only some theme have this problem.

i think the code for this is `.xfce4-panel.background { background-color: rgba(36, 36, 36, 0.8); color: #fcfcfc; font-weight: normal; }` which is from **Greybird/gtk-3.0/gtk.css** CMIIW

**Comment by EliverLara** [comment]
Hi

> i think the code for this is` .xfce4-panel.background { background-color: rgba(36, 36, 36, 0.8); color: #fcfcfc; font-weight: normal;` }

 Does that code snippet work for you?

**Comment by denikris** [comment]
helo again, this is the result after i change the **line 5939** in _**gtk-3.20/gtk.css**_ and _**gtk-3.20/gtk-dark.css**_ from `.xfce4-panel.panel {` to `.xfce4-panel.background {`
![Screenshot_2020-08-18_17-34-54](https://user-images.githubusercontent.com/16707606/90503330-71842700-e179-11ea-8e62-ac1d2c7f8cd2.png)
i'm not sure this is the correct color of panel background but it's feel more uniform for me

**Comment by denikris** [comment]
https://docs.xfce.org/xfce/xfce4-panel/theming also have examples about panel background color

**Comment by EliverLara** [comment]
Done! thanks!
