### ISSUE TITLE
Synaptic UI does not appear with theme

### ISSUE THREAD

**Issue by philipzae** [dracula/gtk#56]
![image](https://user-images.githubusercontent.com/4412114/85645757-b6c13680-b6ab-11ea-8af4-7d650a0e2690.png)

System: Xubuntu 20.04

**Comment by EliverLara** [comment]
Hi, to have the theme working in this type of applications, you must install it in the `/usr/share/themes/ `directory.

**Comment by philipzae** [comment]
Yes that is correct. :D
