### ISSUE TITLE
Text in Hexchat text fields not visible

### ISSUE THREAD

**Issue by philipzae** [dracula/gtk#57]
Can't see the text in the two text fields
![image](https://user-images.githubusercontent.com/4412114/85645898-fee05900-b6ab-11ea-8889-fa6bff91610c.png)

Text highlighted in the fields
![image](https://user-images.githubusercontent.com/4412114/85646074-57aff180-b6ac-11ea-8e38-8cf48a853d16.png)

**Comment by EliverLara** [comment]
Those colors are managed directly from hexchat, you can easily modify them by [following these instructions](https://hexchat.readthedocs.io/en/latest/appearance.html#colors).
