### ISSUE TITLE
There is not the theme in qt5ct

### ISSUE THREAD

**Issue by l4gfcm** [dracula/gtk#64]
I`m trying to use the qt theme from [AUR](https://aur.archlinux.org/packages/ant-dracula-kde-theme-git/) but it is not available in qt5ct.
Thanks in advance.

**Comment by EliverLara** [comment]
Hi @l4gfcm, sorry but I'm not the owner of that AUR, so I can't tell you what's wrong with it.

**Comment by l4gfcm** [comment]
Thank for your answer. I found an another way to use the theme with QT - using qt5-styleplugins.
