### ISSUE TITLE
Problem with Gedit line highlight color

### ISSUE THREAD

**Issue by vishwajeetmallick** [dracula/gtk#65]
Hello, please fix these issues in Dracula GTK theme

1. When Gedit color-scheme is set to Classic, and light highlight option is selected from Gedit preference, text in the current line is indistinguishable from current line.

2. Browser specific CSS (like -moz -webkit) highlighted in yellow and text is unreadable.

3. In EasyTag Application alternating lines unreadable due to background color.
![Screenshot from 2020-07-27 23-46-41](https://user-images.githubusercontent.com/60401131/88577928-60a63100-d065-11ea-8695-b9606615c6ea.png)
![Screenshot from 2020-07-27 23-49-26](https://user-images.githubusercontent.com/60401131/88577930-61d75e00-d065-11ea-91d2-0e34f4ff7df0.png)
![Screenshot from 2020-07-27 23-59-24](https://user-images.githubusercontent.com/60401131/88577931-626ff480-d065-11ea-89ef-3d31c6554427.png)

**Comment by EliverLara** [comment]
Hi @vishwajeetmallick, they both seem to be old app issues when you use a dark theme, as you can see [here](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/29) and [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758859).

Gedit issue: 

Arc dark | Adwaita dark 
------ | ----- 
![Captura de pantalla de 2020-07-29 14-26-12](https://user-images.githubusercontent.com/9838260/88851023-c8699280-d1b1-11ea-9718-a6f8baf4cc22.png) | ![Captura de pantalla de 2020-07-29 14-25-48](https://user-images.githubusercontent.com/9838260/88851040-d0293700-d1b1-11ea-9f88-dc9b4b528876.png)

**Comment by vishwajeetmallick** [comment]
Thanks EliverLara. I will be reporting this issue to Gnome then.
