### ISSUE TITLE
[Request] standard button for Alt variant and some element are mixed pink and purple

### ISSUE THREAD

**Issue by denikris** [dracula/gtk#66]
![Screenshot from 2020-08-10 00-18-18](https://user-images.githubusercontent.com/16707606/89737953-40cc2f80-da9f-11ea-887a-52f32fe7bf25.png)
in alternative variant, gnome-shell and gtk2 app (audacious in screenshot) have pink accent whilst other gtk3 apps (tweaks in screenshot) have purple

**Comment by EliverLara** [comment]
Fixed!
