### ISSUE TITLE
Install Fails on KDE Plasma

### ISSUE THREAD

**Issue by barkb** [dracula/gtk#68]
Trying to install theme on KDE Plasma through global theme browser in system settings fails with the error: "Installation of /tmp/fLQfBE-Dracula.tar.xz failed: Could not install dependency: 'kns://plasma-themes.knsrc/api.kde-look.org/1370687'"
Screenshot of error included below
![Screenshot_20200902_142022](https://user-images.githubusercontent.com/22268733/92026954-745d4b00-ed27-11ea-96ef-ec643eac49d7.png)

**Comment by EliverLara** [comment]
Hi, Does this still persis?

**Comment by barkb** [comment]
Installing from the global theme downloader works, however when trying to install the plasma style, that still fails with the error: "Installation of /tmp/DbQKfO-Dracula.tar.xz failed: No metadata file in package: /tmp/DbQKfO-Dracula.tar.xz"

**Comment by EliverLara** [comment]
Fixed! thanks for reporting.
