### ISSUE TITLE
White context, notification, "settings" menus

### ISSUE THREAD

**Issue by slottwo** [dracula/gtk#70]
System informations:
- OS: Pop!_OS 20.04 LTS x86_64 
- Kernel: 5.4.0-7642-generic 
- Shell: bash 5.0.17 
- DE: GNOME 
- WM: Mutter 
- WM Theme: Dracula 
- Theme: gtk-master [GTK2/3] 
- Icons: Pop [GTK2/3] 

I don't know if it was intentional, but I think that these colors (white / orange / blue) run away from the "dark" dracula theme

![Captura de tela de 2020-09-08 11-07-27](https://user-images.githubusercontent.com/41028091/92487420-9b9e9700-f1c3-11ea-9e04-5f375b2abc00.png)
![Captura de tela de 2020-09-08 11-08-00](https://user-images.githubusercontent.com/41028091/92487424-9ccfc400-f1c3-11ea-8163-8b3ee31054fa.png)
![Captura de tela de 2020-09-08 11-08-06](https://user-images.githubusercontent.com/41028091/92487426-9ccfc400-f1c3-11ea-8236-b24d75f4a7cf.png)

**Comment by EliverLara** [comment]
Hi, It seems that you have not applied the shell theme, you have to install [this](https://extensions.gnome.org/extension/19/user-themes/) extension and then select 'sweet' in the shell section of tweaks.

**Comment by slottwo** [comment]
It's works! I had just reinstalled pop os, so I forgot about that extension, sorry and thanks.

**Comment by brccabral** [comment]
This instruction should be in the "INSTALL.md" and at draculatheme.com/gtk
