### ISSUE TITLE
Buttons moving in application menu

### ISSUE THREAD

**Issue by pranshuj73** [dracula/gtk#71]
I'm using Ubuntu 20.04 and in the applications menu i noticed that when i used the theme the buttons are moving almost as if vibrating. Please see the attached screen recoding.

System information:
+ OS: Ubuntu 20.04 LTS x86_64
+ Kernel: 5.4.0-47-generic
+ DE: Gnome
+ Icons: Tela Circle

[Link to the screen recording](https://imgur.com/kFUECa1)

**Comment by denikris** [comment]
idk if this is related, but some user upgrade from 19.10 or fresh install also have this problem with this on yaru theme
https://askubuntu.com/questions/1241165/should-i-report-show-applications-not-scrolling-as-a-bug
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1879600

**Comment by volt9801** [comment]
> idk if this is related, but some user upgrade from 19.10 or fresh install also have this problem with this on yaru theme
> https://askubuntu.com/questions/1241165/should-i-report-show-applications-not-scrolling-as-a-bug
> https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1879600

it could be, i'm facing the same bug too and i did a fresh install
