### ISSUE TITLE
Icons were not changed

### ISSUE THREAD

**Issue by vicentenoriega** [dracula/gtk#72]
Hi,

I applied Dracula theme almost successfully. The last thing that I wasn't able to change was the icons.

"Dracula" **does not appear on the Icons selector** on gnome-tweak-tools.

![image](https://user-images.githubusercontent.com/22145110/92885675-4a84e200-f413-11ea-8f4b-2abdda8707f2.png)

![image](https://user-images.githubusercontent.com/22145110/92886596-10681000-f414-11ea-939b-067b0885e9e4.png)

**Comment by EliverLara** [comment]
Hi, icons are not provided as a part of the theme, anyway, here you have the mix  [Dracula.zip](https://github.com/dracula/gtk/files/5214861/Dracula.zip)

**Comment by vicentenoriega** [comment]
> Hi, icons are not provided as a part of the theme, anyway, here you have the mix [Dracula.zip](https://github.com/dracula/gtk/files/5214861/Dracula.zip)

Thank you :) :+1:

**Comment by thiagolucio** [comment]
Icon Pack is not part of the theme. It is a separate package.
I particularly like it a lot and it matches the Tela Icon Theme package very well. I usually use it in the Dracula theme color. It is easy to install and also has the dark color used by the theme image pack. But I would nominate Purple Dark for the theme.

https://www.gnome-look.org/p/1279924/

I suggest clone the GitHub repo directly inside the ".icons" directory and run the command inside this directory 
`sudo ./install.sh purple`

But in the repository, you find all install instructions you need. 
https://github.com/vinceliuice/Tela-icon-theme
:)

> > Hi, icons are not provided as a part of the theme, anyway, here you have the mix [Dracula.zip](https://github.com/dracula/gtk/files/5214861/Dracula.zip)
> 
> Thank you :)
