### ISSUE TITLE
PopOS: Light Theme despite having Dracula on

### ISSUE THREAD

**Issue by faedy2** [dracula/gtk#73]
![screenshot](https://user-images.githubusercontent.com/12666920/93022185-c159e080-f5b5-11ea-9e5d-dfeebf8dcbaf.png)
This occurs on pop-ups like login prompts as well

**Comment by EliverLara** [comment]
Hi, please take a look to #70

**Comment by faedy2** [comment]
Thank you. That was the fix :+1:
