### ISSUE TITLE
[Request] Timeshift still light themed

### ISSUE THREAD

**Issue by faedy2** [dracula/gtk#74]
I'm not experienced with theme creation, but is there any way that I can help to make it dark-themed?
![Screenshot from 2020-09-13 18-57-34](https://user-images.githubusercontent.com/12666920/93030799-d3f30a80-f5f3-11ea-9ae4-f0b00305e638.png)

**Comment by EliverLara** [comment]
Hi, for those apps that use `sudo` permissions, you must to install the theme in `/usr/share/themes/`.
