### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by SecurityInsanity** [dracula/gtk#76]
Can we get a new release of this package? I'd like to update: https://aur.archlinux.org/packages/ant-dracula-gtk-theme as we have some users who want to get new alternative colors that were seemingly released ~june.

**Comment by EliverLara** [comment]
Hi, the new release is [now available](https://github.com/dracula/gtk/releases/tag/v2.0).

**Comment by SecurityInsanity** [comment]
Thanks so much!
