### ISSUE TITLE
Deja Dup light, but other applications dark

### ISSUE THREAD

**Issue by faedy2** [dracula/gtk#78]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![2020-09-21_21-11](https://user-images.githubusercontent.com/12666920/93835978-0d102800-fc4f-11ea-8bbb-a646dbd23f85.png)
I have installed the theme in /usr/share/themes

**Comment by Jimmysit0** [comment]
Mine looks the same. Did you fix it?

**Comment by faedy2** [comment]
Not yet

**Comment by EliverLara** [comment]
Hi, on my side the application is perfectly themed,  Are you sure the application was not installed via snap, or flatpak?

![Captura de pantalla de 2020-10-21 12-52-38](https://user-images.githubusercontent.com/9838260/96758845-eacc1000-139c-11eb-9a76-ef54516ac692.png)

**Comment by Jimmysit0** [comment]
> Hi, on my side the application is perfectly themed, Are you sure the application was not installed via snap, or flatpak?
> 
> ![Captura de pantalla de 2020-10-21 12-52-38](https://user-images.githubusercontent.com/9838260/96758845-eacc1000-139c-11eb-9a76-ef54516ac692.png)

Intentare descargarlo nuevamente, en caso de que no funcione te informare, permiteme un momento te dire por que via lo estoy descargando.

**Comment by Jimmysit0** [comment]
https://draculatheme.com/gtk Lo estoy descargando desde alli, lo cual me descarga un archivo .zip, que a la hora de extraerlo y hacerlo mi tema de gtk3, queda igual que antes, es decir, se ve igual al de "faedy2", capturas en unos momentos.

**Comment by Jimmysit0** [comment]
![image](https://user-images.githubusercontent.com/69643443/96778006-a9456000-13b0-11eb-8522-9199bd1a73fe.png)

**Comment by Jimmysit0** [comment]
Automaticamente queda asi

**Comment by faedy2** [comment]
Fixed when installing the deb package rather than the flatpak
