### ISSUE TITLE
Icons not changing

### ISSUE THREAD

**Issue by yAya-yns** [dracula/gtk#79]
Hi,

I really enjoy using this theme. However, the icons don't change for me.

I tried ```gsettings set org.gnome.desktop.interface icon-theme "Dracula"```. Command executed without error return, but it changed to an icon theme that looks like "Hicolor" instead of what you showed in the screenshot.

I also tried to modify in gnome tweak tools. However, I can't find the Dracula theme for icons in the tweak tools. 

![image](https://user-images.githubusercontent.com/33261653/94438270-e4b38c80-016c-11eb-9b71-e50f4d8095e3.png)

![image](https://user-images.githubusercontent.com/33261653/94438011-85ee1300-016c-11eb-854c-3d745cdc793a.png)

**Comment by EliverLara** [comment]
Hi @yAya-yns , please take a look to #72

**Comment by yAya-yns** [comment]
Thank you!
