### ISSUE TITLE
Calendar items in Gnome-Shell 3.38 not themed

### ISSUE THREAD

**Issue by aquatix** [dracula/gtk#82]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Gnome-shell moved the calendar items to be displayed under the calendar instead of in the same column as the notifications. However, this new block does not have the Dracula theming, but is brownish. (see screenshot).

It's a minor detail, but it would be great to have it resolved.

Thanks very much for Draculising my desktop :)

**Comment by aquatix** [comment]
Hm, I cannot upload a screenshot here? Will try to upload it somewhere else and link it here. Thanks in advance!

**Comment by owainharris** [comment]
Porting the theme as a Snap Package would resolve this. The Software Center has the same [issue](https://github.com/dracula/gtk/issues/45). 

Currently looking into how to create a Snap Package myself.

**Comment by aquatix** [comment]
How is that supposed to help? I already have the latest master checked out locally and using that as theme. Works great, except for that little calendar items box that's new in Gnome 3.38.

I'm unsure about how a snap package would fare better.

Also as an aside, not a fan of snaps, uninstalled snapd here :)

Anyway, thanks for thinking along! Snaps will be useful for others, for ease of install. (Also, flatpack? Myself I'm an oldfashioned .deb installer, or just use a Git checkout or tarball :) ).

**Comment by owainharris** [comment]
@aquatix I presumed you might have had the Calendar app installed as a Snap (I think Ubuntu ships it by default like that along with the Software Center and Calculator etc). Basically, the theme needs to be a Snap also for Snap packages to use.

Anyway - looks like this is not your issue then.

**Comment by aquatix** [comment]
Ah right, makes sense, but no, that's not the case. I was wondering how a snap-sandboxed theme would solve this, but now I understand your reasoning.

No, it's not the Calendar app even, it's the little calendar widget in the dropdown of the clock in the Gnome-shell panel, similar to the list of notifications in the same area. I tried making a screenshot of it, but somehow it failed to keep that dropdown open/visible when taking the shot.

**Comment by fernandomhahne** [comment]
I have the same problem in Fedora 33:

![Captura de tela de 2020-10-24 14-59-14](https://user-images.githubusercontent.com/2737027/97088778-94afd480-1609-11eb-9844-ec4ae5dff422.png)
