### ISSUE TITLE
Rounded corners on tiled windows

### ISSUE THREAD

**Issue by sagischwarz** [dracula/gtk#85]
Hi,

first: thank you so much for this wonderful theme and all the work that went into creating it!

I'm using the KDE global theme and there is one little detail that got my attention. When tiling the applications by snapping them on the edges of the screen, the corners adjacent to each other and to the edge of the screen stay rounded, leaving a little hole.

![2020-11-09_12-03_1](https://user-images.githubusercontent.com/6792072/98534013-1fd4cf80-2284-11eb-9ac3-6de7d2c439c7.png)
![2020-11-09_12-03](https://user-images.githubusercontent.com/6792072/98534016-206d6600-2284-11eb-88dc-c3a31d52dce1.png)

Can the theme be configured to disable rounded  corners for tiled windows?

Thanks again and please let me know if you need more information.

**Comment by EliverLara** [comment]
I think it's not possible due to aurorae theming limitations.
