### ISSUE TITLE
gnome-shell menus and drop down seem to brown

### ISSUE THREAD

**Issue by dbasinge** [dracula/gtk#92]
The dropdown and menu backgrounds seem to brown.
![Screenshot from 2021-02-07 11-54-33](https://user-images.githubusercontent.com/2634758/107156416-69908d00-693b-11eb-90b0-aae017d376b0.png)
![Screenshot from 2021-02-07 11-54-21](https://user-images.githubusercontent.com/2634758/107156421-6bf2e700-693b-11eb-8ce6-7a6243e5bbbc.png)

> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by kikifuku** [comment]
I am experiencing the same issue. How did you solve this?
