### ISSUE TITLE
gnome-shell using white backgrounds in menus

### ISSUE THREAD

**Issue by dbasinge** [dracula/gtk#97]
gnome-shell using white backgrounds in menus. Other dark theme work properly.

![Screenshot from 2021-02-27 08-19-43](https://user-images.githubusercontent.com/2634758/109391533-cd6ffb00-78d4-11eb-8c7c-134488647858.png)

**Comment by EliverLara** [comment]
Hi, Could you provide more info about your OS, please?

**Comment by dbasinge** [comment]
Fedora 33 with Gnome 3.38.3
