### ISSUE TITLE
Why hasn't the Git AUR version of Dracula GTK been updated?

### ISSUE THREAD

**Issue by NovaViper** [dracula/gtk#98]
Hey guys, I noticed that the git version of the dracula AUR still hasn't been updated to use the new dracula repo link.

https://aur.archlinux.org/packages/ant-dracula-theme-git

Will this one ever get updated?

**Comment by PurpleUltraViolet** [comment]
See #51 - probably not.
It redirects just fine so it is probably a non-issue.
